### ISSUE TITLE
Queue demand error

### ISSUE THREAD

**Issue by sergey-lukianov** [Buckitup-chat/chat#311]
```

08:26:18.572 [error] GenServer Chat.Db.MainDb.Writer terminating
** (stop) exited in: GenServer.call(Chat.Db.MainDb.Queue, :demand, 5000)
    ** (EXIT) time out
    (elixir 1.14.1) lib/gen_server.ex:1038: GenServer.call/3
    (chat 0.1.0) lib/chat/db/pipeline/writer.ex:39: Chat.Db.Pipeline.Writer.demand_queue/1
    (chat 0.1.0) lib/chat/db/pipeline/writer_process.ex:45: Chat.Db.Pipeline.WriterProcess.handle_continue/2
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:865: :gen_server.loop/7
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:continue, :demand}
State: {:w_state, Chat.Db.MainDb, "/root/storage/main_db/v.9_files", Chat.Db.MainDb.Queue, Chat.Db.MainDb.Compactor, 0, #Reference<0.2552121402.269484033.143870>}
```

**Comment by sviatosluv** [comment]
@sergey-lukianov It seems to be an old codebase?!
