### ISSUE TITLE
Admin panel wifi rename - not working

### ISSUE THREAD

**Issue by buckitupnet** [Buckitup-chat/chat#313]
When try to rename wifi SSID the page refreshes but change is not saved (the connection is not lost)

**Comment by sergey-lukianov** [comment]
```
08:54:58.225 [error] GenServer #PID<0.3814.0> terminating
** (KeyError) key :room_map not found in: #Phoenix.LiveView.Socket<id: "phx-F1uVFKhUFiVcJk-B", endpoint: ChatWeb.Endpoint, view: ChatWeb.MainLive.Index, parent_pid: nil, root_pid: #PID<0.3814.0>, router: ChatWeb.Router, assigns: %{timezone: "Europe/Kiev", is_admin: true, changeset: nil, uploads: %{__phoenix_refs_to_names__: %{"phx-AAAABjgsqj3_OjMD" => :file, "phx-AAAABjhwZ_f_OjMj" => :my_keys_file}, file: #Phoenix.LiveView.UploadConfig<name: :file, max_entries: 2000, max_file_size: 102400000000, entries: [], accept: :any, ref: "phx-AAAABjgsqj3_OjMD", errors: [], auto_upload?: true, progress_event: &ChatWeb.LiveHelpers.Uploader.handle_progress/3, ...>, my_keys_file: #Phoenix.LiveView.UploadConfig<name: :my_keys_file, max_entries: 1, max_file_size: 1024000000, entries: [], accept: :any, ref: "phx-AAAABjhwZ_f_OjMj", errors: [], auto_upload?: true, progress_event: #Function<1.697705/3 in ChatWeb.MainLive.Index.handle_progress>, ...>}, logout_step: nil, flash: %{}, room_count_to_backup: 31, room_list: [#Chat.Rooms.Room<name: "0", type: :public, ...>, #Chat.Rooms.Room<name: "22", type: :public, ...>, #Chat.Rooms.Room<name: "carg", type: :public, ...>, #Chat.Rooms.Room<name: "1", type: :public, ...>], need_login: false, dialog: nil, __changed__: %{}, live_action: :index, users: [#Chat.Card<name: "r3", ...>, #Chat.Card<name: "old mobile", ...>, #Chat.Card<name: "test", ...>], wifi_ssid: "buckItUp.app", wifi_loaded: true, user_list: [#Chat.Card<name: "old mobile", ...>, #Chat.Card<name: "test", ...>], live_modal: nil, handshaked: true, backup_settings: %Chat.Admin.BackupSettings{type: :regular}, uploads_metadata: %{}, admin_list: [#Chat.Card<name: "r3", ...>], version: "2023-05-01_344a783___2023-05-03_059ad40", room: nil, my_id: <<2, 121, 128, 53, 117, 216, 113, 218, 157, 3, 136, 30, 181, 134, 157, 117, 230, 109, 217, ...>>, media_settings: %Chat.Admin.MediaSettings{functionality: :cargo}, me: #Chat.Identity<name: "r3", ...>, joined_rooms: [#Chat.Rooms.Room<name: "0", type: :public, ...>, #Chat.Rooms.Room<name: "22", type: :public, ...>, #Chat.Rooms.Room<name: "carg", type: :public, ...>], monotonic_offset: 2259563528, wifi_password: "2551C7AF8288DAC41154C70CBB462794E612E6B07351289B214FE268A68B7850", locale: "en-GB", mode: :lobby, db_status: %{compacting: false, flags: [], mode: :main, writable: :yes}, full_user_list: [#Chat.Card<name: "old mobile", ...>, #Chat.Card<name: "r3", ...>, #Chat.Card<name: "test", ...>], free_spaces: %{internal_db: "2210 MB", main_db: "11381 MB", media_db: "Not found"}, timezone_offset: 3, new_rooms: [#Chat.Rooms.Room<name: "1", type: :public, ...>], room_map: %{<<2, 2, 211, 239, 109, ...>> => #Chat.Identity<name: "", ...>, <<2, 30, 102, 95, ...>> => #Chat.Identity<name: "", ...>, <<2, 81, 168, ...>> => #Chat.Identity<name: "", ...>, <<2, 98, ...>> => #Chat.Identity<name: "", ...>, <<2, ...>> => #Chat.Identity<name: "", ...>, <<...>> => #Chat.Identity<...>, ...}, cargo_room: nil, cargo_settings: %Chat.Admin.CargoSettings{checkpoints: [<<2, 121, ...>>, <<2, ...>>]}, lobby_mode: :admin, peer: nil, rooms: [#Chat.Identity<...>, ...], image_gallery: nil, ...}, transport_pid: #PID<0.3812.0>, ...>
    (chat 0.1.0) lib/chat_web/live/main_live/page/admin_panel.ex:58: ChatWeb.MainLive.Page.AdminPanel.set_wifi/3
    (chat 0.1.0) lib/chat_web/live/main_live/index.ex:308: ChatWeb.MainLive.Index.handle_event/3
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/channel.ex:401: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.2.1) /Users/lukianov/work/buckitUp/platform/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/channel.ex:221: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F1uVFKhUFiVcJk-B", event: "event", payload: %{"event" => "admin/wifi-submit", "type" => "form", "value" => "ssid=buckItUp1.app&password=1q2w3e4r5t"}, ref: "54", join_ref: "24"}
State: %{components: {%{1 => {ChatWeb.MainLive.Admin.MediaSettingsForm, :media_settings_form, %{__changed__: %{}, changeset: #Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #Chat.Admin.MediaSettings<>, valid?: true>, flash: %{}, id: :media_settings_form, media_settings: %Chat.Admin.MediaSettings{functionality: :cargo}, myself: %Phoenix.LiveComponent.CID{cid: 1}}, %{__changed__: %{}, lifecycle: %Phoenix.LiveView.Lifecycle{handle_event: [], handle_info: [], handle_params: [], mount: [], after_render: []}, root_view: ChatWeb.MainLive.Index}, {100702817858699706650625264827701828425, %{0 => {118970292807654719229453556541006727223, %{3 => {194211515565045072380156500110444018881, %{0 => 290248024486611673602918279270887705848}}}}}}}, 2 => {ChatWeb.MainLive.Admin.BackupSettingsForm, :backup_settings_form, %{__changed__: %{}, backup_settings: %Chat.Admin.BackupSettings{type: :regular}, changeset: #Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #Chat.Admin.BackupSettings<>, valid?: true>, flash: %{}, id: :backup_settings_form, myself: %Phoenix.LiveComponent.CID{cid: 2}}, %{__changed__: %{}, lifecycle: %Phoenix.LiveView.Lifecycle{handle_event: [], handle_info: [], handle_params: [], mount: [], after_render: []}, root_view: ChatWeb.MainLive.Index}, {39643890711729702405879403168076618225, %{0 => {118970292807654719229453556541006727223, %{3 => {214667647499013623286470273493868985177, %{0 => 60841307339368280664237841904276103227}}}}}}}, 3 => {ChatWeb.MainLive.Admin.CargoSettingsForm, :cargo_settings_form, %{__changed__: %{}, cargo_settings: %Chat.Admin.CargoSettings{checkpoints: [<<2, 121, 128, 53, 117, 216, 113, 218, 157, 3, 136, 30, 181, 134, 157, 117, 230, 109, 217, 124, 24, 239, 107, 61, 219, 4, 252, 48, 114, 11, 184, 159, 208>>, <<2, 193, 31, 188, 238, 209, 206, 190, 129, 102, 56, 5, 28, 39, 7, 127, 185, 144, 55, 199, 141, 190, 179, 247, 26, 9, 8, 219, 0, 49, 147, 28, 81>>]}, checkpoints: [{<<2, 121, 128, 53, 117, 216, 113, 218, 157, 3, 136, 30, 181, 134, 157, 117, 230, 109, 217, 124, 24, 239, 107, 61, 219, 4, 252, 48, 114, 11, 184, 159, 208>>, "r3"}, {<<2, 193, 31, 188, 238, 209, 206, 190, 129, 102, 56, 5, 28, 39, 7, 127, 185, 144, 55, 199, 141, 190, 179, 247, 26, 9, 8, 219, 0, 49, 147, 28, 81>>, "test"}], flash: %{}, id: :cargo_settings_form, myself: %Phoenix.LiveComponent.CID{cid: 3}, rest: [{<<2, 79, 30, 149, 167, 63, 115, 166, 255, 111, 48, 96, 50, 207, 7, 55, 94, 115, 84, 152, 103, 167, 190, 158, 49, 59, 240, 178, 172, 1, 43, 225, 55>>, "old mobile"}], selected_pub_key: nil, selected_type: nil, users: [{<<2, 79, 30, 149, 167, 63, 115, 166, 255, 111, 48, 96, 50, 207, 7, 55, 94, 115, 84, 152, 103, 167, 190, 158, 49, 59, 240, 178, 172, 1, ...>>, "old mobile"}, {<<2, 121, 128, 53, 117, 216, 113, 218, 157, 3, 136, 30, 181, 134, 157, 117, 230, 109, 217, 124, 24, 239, 107, 61, 219, 4, 252, 48, 114, ...>>, "r3"}, {<<2, 193, 31, 188, 238, 209, 206, 190, 129, 102, 56, 5, 28, 39, 7, 127, 185, 144, 55, 199, 141, 190, 179, 247, 26, 9, 8, 219, ...>>, "test"}]}, %{__changed__: %{}, lifecycle: %Phoenix.LiveView.Lifecycle{handle_event: [], handle_info: [], handle_params: [], mount: [], after_render: []}, root_view: ChatWeb.MainLive.Index}, {252661114923736217023958088664588895286, %{0 => {143193600799888575794423557229550372964, %{1 => {21548813462989539318554287732442792817, %{2 => 313393674223166020433098262956655914681}}}}, 1 => {77354929664404933643312727841023836714, %{0 => {116165191550086667562357982004543920348, %{}}, 1 => {116165191550086667562357982004543920348, %{}}}}, 2 => {143193600799888575794423557229550372964, %{1 => {21548813462989539318554287732442792817, %{2 => 313393674223166020433098262956655914681}}}}}}}}, %{ChatWeb.MainLive.Admin.BackupSettingsForm => %{backup_settings_form: 2}, ChatWeb.MainLive.Admin.CargoSettingsForm => %{cargo_settings_form: 3}, ChatWeb.MainLive.Admin.MediaSettingsForm = (truncated)
```
