### ISSUE TITLE
503 on upload

### ISSUE THREAD

**Issue by sergey-lukianov** [Buckitup-chat/chat#341]
Discover why this could happen. Check supervision

```
2023-05-12 07:16:44.541000 [info] PUT /upload_chunk/3915ed932b6bdfa0485bd5a33d18408cf2a85a35b692a3e7a61a0a6b74fccdd3
2023-05-12 07:16:44.542000 [debug] Processing with ChatWeb.UploadChunkController.put/2
  Parameters: %{"key" => "3915ed932b6bdfa0485bd5a33d18408cf2a85a35b692a3e7a61a0a6b74fccdd3"}
  Pipelines: []
2023-05-12 07:16:44.543000 [error] [upload] error processing chunk {:empty_initial_secret, true}
2023-05-12 07:16:44.543000 [info] Sent 503 in 2ms
2023-05-12 07:16:45.604000 [info] PUT /upload_chunk/3915ed932b6bdfa0485bd5a33d18408cf2a85a35b692a3e7a61a0a6b74fccdd3
2023-05-12 07:16:45.604000 [debug] Processing with ChatWeb.UploadChunkController.put/2
```

**Comment by sergey-lukianov** [comment]
Compactor just died
```
2023-05-12 07:16:25.038000 [error] GenServer Chat.Db.BackupDb terminating
** (ArithmeticError) bad argument in arithmetic expression
    :erlang.+(nil, 1)
    (cubdb 2.0.1) lib/cubdb.ex:1561: anonymous fn/1 in CubDB.new_compaction_store/1
    (cubdb 2.0.1) lib/cubdb.ex:1561: CubDB.new_compaction_store/1
    (cubdb 2.0.1) lib/cubdb.ex:1499: CubDB.trigger_compaction/1
    (cubdb 2.0.1) lib/cubdb.ex:1373: CubDB.handle_call/3
    (stdlib 4.1.1) gen_server.erl:1149: :gen_server.try_handle_call/4
    (stdlib 4.1.1) gen_server.erl:1178: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message (from Chat.Db.BackupDb.Compactor): :compact
State: %CubDB.State{task_supervisor: #PID<0.7184.0>, btree: %CubDB.Btree{root: {:l, [db_type: 1038]}, root_loc: 1061, size: 1, dirt: 2, store: %CubDB.Store.File{pid: #PID<0.7182.0>, file_path: "/root/media/backup_db/v.9/0.cub"}, capacity: 32}, data_dir: "/root/media/backup_db/v.9", compactor: nil, compacting_store: nil, clean_up: #PID<0.7183.0>, clean_up_pending: false, old_btrees: [], readers: %{}, auto_compact: false, auto_file_sync: false, subs: [], writer: nil, write_queue: {[], []}}
Client Chat.Db.BackupDb.Compactor is alive

    (stdlib 4.1.1) gen.erl:237: :gen.do_call/4
    (elixir 1.14.1) lib/gen_server.ex:1035: GenServer.call/3
    (chat 0.1.0) lib/chat/db/pipeline/compactor.ex:51: Chat.Db.Pipeline.Compactor.handle_info/2
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
2023-05-12 07:16:25.047000 [error] GenServer #PID<0.7184.0> terminating
** (ArithmeticError) bad argument in arithmetic expression
    :erlang.+(nil, 1)
    (cubdb 2.0.1) lib/cubdb.ex:1561: anonymous fn/1 in CubDB.new_compaction_store/1
    (cubdb 2.0.1) lib/cubdb.ex:1561: CubDB.new_compaction_store/1
    (cubdb 2.0.1) lib/cubdb.ex:1499: CubDB.trigger_compaction/1
    (cubdb 2.0.1) lib/cubdb.ex:1373: CubDB.handle_call/3
    (stdlib 4.1.1) gen_server.erl:1149: :gen_server.try_handle_call/4
    (stdlib 4.1.1) gen_server.erl:1178: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.7181.0>, {:badarith, [{:erlang, :+, [nil, 1], [error_info: %{module: :erl_erts_errors}]}, {CubDB, :"-new_compaction_store/1-fun-1-", 1, [file: 'lib/cubdb.ex', line: 1561]}, {CubDB, :new_compaction_store, 1, [file: 'lib/cubdb.ex', line: 1561]}, {CubDB, :trigger_compaction, 1, [file: 'lib/cubdb.ex', line: 1499]}, {CubDB, :handle_call, 3, [file: 'lib/cubdb.ex', line: 1373]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 1149]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 1178]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
State: %DynamicSupervisor{args: {{:temporary, 5000}, []}, extra_arguments: [], mod: Task.Supervisor, name: {#PID<0.7184.0>, Task.Supervisor}, strategy: :one_for_one, max_children: :infinity, max_restarts: 3, max_seconds: 5, children: %{}, restarts: []}
```

**Comment by sergey-lukianov** [comment]
https://files.slack.com/files-pri/T0DNVG57B-F0585HMPBQQ/uploader_stuck_log.txt
