### ISSUE TITLE
Handle mount errors

### ISSUE THREAD

**Issue by sergey-lukianov** [Buckitup-chat/chat#478]
mount error breaks stages, we need to handle mount error

```
** (MatchError) no match of right hand side value: {"", 255}
    (platform 0.1.2) lib/platform/storage/device.ex:23: Platform.Storage.Device.mount_on/2
    (elixir 1.14.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<1.89489099/0 in Platform.Storage.Mounter.on_msg/2>
    Args: []
2023-09-07 08:13:55.017000 [debug] Platform.Storage.Mounter terminated from :terminate w/ reason: {:function_clause,
 [
   {Platform.Storage.Mounter, :on_msg,
    [
      {:DOWN, #Reference<0.3233696196.268500993.96510>, :process,
       #PID<0.3725.0>,
       {{:badmatch, {"", 255}},
        [
          {Platform.Storage.Device, :mount_on, 2,
           [file: 'lib/platform/storage/device.ex', line: 23]},
          {Task.Supervised, :invoke_mfa, 2,
           [file: 'lib/task/supervised.ex', line: 89]},
          {Task.Supervised, :reply, 4,
           [file: 'lib/task/supervised.ex', line: 34]},
          {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}
        ]}},
      %{
        device: "sda",
        next_specs: [
          %{
            id: Chat.Db.MainDbSupervisor,
            shutdown: 20000,
            start: {Chat.Db.MainDbSupervisor, :start_link,
             ["/root/storage/main_db/v.9"]},
            type: :supervisor
          },
          {Platform.Storage.Bouncer, [db: Chat.Db.MainDb, type: "main_db"]},
          %{
            id: Platform.Storage.InternalToMain.Starter,
            shutdown: 1000,
            start: {Platform.Storage.InternalToMain.Starter, :start_link, [[]]}
          },
          %{
            id: Platform.App.MainStages.Copying,
            shutdown: 6000,
            start: {DynamicSupervisor, :start_link,
             [
               [
                 name: Platform.App.MainStages.Copying,
                 strategy: :one_for_one,
                 max_restarts: 0
               ]
             ]},
            type: :supervisor
          },
          %{
            id: Platform.Storage.InternalToMain.Copier,
            shutdown: 25000,
            start: {Platform.Storage.InternalToMain.Copier, :start_link,
             [
               [
                 task_in: Platform.App.Db.MainDbSupervisor.Tasks,
                 next: [
                   under: Platform.App.MainStages.Copying,
                   run: [
                     Platform.Storage.MainReplicator,
                     %{
                       id: Platform.Storage.InternalToMain.Switcher,
                       shutdown: 1000,
                       start: {Platform.Storage.InternalToMain.Switcher,
                        :start_link, [[]]}
                     }
                   ]
                 ]
               ]
             ]}
          }
        ],
        next_supervisor: Platform.App.MainStages.Mounting,
        path: "/root/storage",
        task_ref: #Reference<0.3233696196.268500993.96510>,
        task_supervisor: Platform.App.Db.MainDbSupervisor.Tasks
      }
    ], [file: 'lib/platform/storage/mounter.ex', line: 28]},
   {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 1123]},
   {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 1200]},
   {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}
 ]}
2023-09-07 08:13:55.023000 [warn] mount cleanup /root/storage {:function_clause, [{Platform.Storage.Mounter, :on_msg, [{:DOWN, #Reference<0.3233696196.268500993.96510>, :process, #PID<0.3725.0>, {{:badmatch, {"", 255}}, [{Platform.Storage.Device, :mount_on, 2, [file: 'lib/platform/storage/device.ex', line: 23]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 4, [file: 'lib/task/supervised.ex', line: 34]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}, %{device: "sda", next_specs: [%{id: Chat.Db.MainDbSupervisor, shutdown: 20000, start: {Chat.Db.MainDbSupervisor, :start_link, ["/root/storage/main_db/v.9"]}, type: :supervisor}, {Platform.Storage.Bouncer, [db: Chat.Db.MainDb, type: "main_db"]}, %{id: Platform.Storage.InternalToMain.Starter, shutdown: 1000, start: {Platform.Storage.InternalToMain.Starter, :start_link, [[]]}}, %{id: Platform.App.MainStages.Copying, shutdown: 6000, start: {DynamicSupervisor, :start_link, [[name: Platform.App.MainStages.Copying, strategy: :one_for_one, max_restarts: 0]]}, type: :supervisor}, %{id: Platform.Storage.InternalToMain.Copier, shutdown: 25000, start: {Platform.Storage.InternalToMain.Copier, :start_link, [[task_in: Platform.App.Db.MainDbSupervisor.Tasks, next: [under: Platform.App.MainStages.Copying, run: [Platform.Storage.MainReplicator, %{id: Platform.Storage.InternalToMain.Switcher, shutdown: 1000, start: {Platform.Storage.InternalToMain.Switcher, :start_link, [[]]}}]]]]}}], next_supervisor: Platform.App.MainStages.Mounting, path: "/root/storage", task_ref: #Reference<0.3233696196.268500993.96510>, task_supervisor: Platform.App.Db.MainDbSupervisor.Tasks}], [file: 'lib/platform/storage/mounter.ex', line: 28]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 1123]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 1200]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}
2023-09-07 08:13:55.030000 [error] GenServer #PID<0.3724.0> terminating
** (FunctionClauseError) no function clause matching in Platform.Storage.Mounter.on_msg/2
    (platform 0.1.2) lib/platform/storage/mounter.ex:28: Platform.Storage.Mounter.on_msg({:DOWN, #Reference<0.3233696196.268500993.96510>, :process, #PID<0.3725.0>, {{:badmatch, {"", 255}}, [{Platform.Storage.Device, :mount_on, 2, [file: 'lib/platform/storage/device.ex', line: 23]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 4, [file: 'lib/task/supervised.ex', line: 34]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}, %{device: "sda", next_specs: [%{id: Chat.Db.MainDbSupervisor, shutdown: 20000, start: {Chat.Db.MainDbSupervisor, :start_link, ["/root/storage/main_db/v.9"]}, type: :supervisor}, {Platform.Storage.Bouncer, [db: Chat.Db.MainDb, type: "main_db"]}, %{id: Platform.Storage.InternalToMain.Starter, shutdown: 1000, start: {Platform.Storage.InternalToMain.Starter, :start_link, [[]]}}, %{id: Platform.App.MainStages.Copying, shutdown: 6000, start: {DynamicSupervisor, :start_link, [[name: Platform.App.MainStages.Copying, strategy: :one_for_one, max_restarts: 0]]}, type: :supervisor}, %{id: Platform.Storage.InternalToMain.Copier, shutdown: 25000, start: {Platform.Storage.InternalToMain.Copier, :start_link, [[task_in: Platform.App.Db.MainDbSupervisor.Tasks, next: [under: Platform.App.MainStages.Copying, run: [Platform.Storage.MainReplicator, %{id: Platform.Storage.InternalToMain.Switcher, shutdown: 1000, start: {Platform.Storage.InternalToMain.Switcher, :start_link, [[]]}}]]]]}}], next_supervisor: Platform.App.MainStages.Mounting, path: "/root/storage", task_ref: #Reference<0.3233696196.268500993.96510>, task_supervisor: Platform.App.Db.MainDbSupervisor.Tasks})
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.3233696196.268500993.96510>, :process, #PID<0.3725.0>, {{:badmatch, {"", 255}}, [{Platform.Storage.Device, :mount_on, 2, [file: 'lib/platform/storage/device.ex', line: 23]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 4, [file: 'lib/task/supervised.ex', line: 34]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
State: %{device: "sda", next_specs: [%{id: Chat.Db.MainDbSupervisor, shutdown: 20000, start: {Chat.Db.MainDbSupervisor, :start_link, ["/root/storage/main_db/v.9"]}, type: :supervisor}, {Platform.Storage.Bouncer, [db: Chat.Db.MainDb, type: "main_db"]}, %{id: Platform.Storage.InternalToMain.Starter, shutdown: 1000, start: {Platform.Storage.InternalToMain.Starter, :start_link, [[]]}}, %{id: Platform.App.MainStages.Copying, shutdown: 6000, start: {DynamicSupervisor, :start_link, [[name: Platform.App.MainStages.Copying, strategy: :one_for_one, max_restarts: 0]]}, type: :supervisor}, %{id: Platform.Storage.InternalToMain.Copier, shutdown: 25000, start: {Platform.Storage.InternalToMain.Copier, :start_link, [[task_in: Platform.App.Db.MainDbSupervisor.Tasks, next: [under: Platform.App.MainStages.Copying, run: [Platform.Storage.MainReplicator, %{id: Platform.Storage.InternalToMain.Switcher, shutdown: 1000, start: {Platform.Storage.InternalToMain.Switcher, :start_link, [[]]}}]]]]}}], next_supervisor: Platform.App.MainStages.Mounting, path: "/root/storage", task_ref: #Reference<0.3233696196.268500993.96510>, task_supervisor: Platform.App.Db.MainDbSupervisor.Tasks}
```

**Comment by buckitupnet** [comment]
ls this also about indication?

**Comment by salseeg** [comment]
Fixed in Buckitup-chat/platform@0b40e9c — added `:DOWN` handler in `Mounter.on_msg/2` so mount failures stop the process gracefully with `{:mount_failed, reason}` instead of crashing with `FunctionClauseError`.
