### ISSUE TITLE
DriveDetector gets terminated

### ISSUE THREAD

**Issue by sviatosluv** [Buckitup-chat/chat#490]
````
 RingLogger.next

10:18:31.597 [info] usb 1-1.4: new high-speed USB device number 4 using xhci_hcd

10:18:31.720 [info] usb 1-1.4: New USB device found, idVendor=090c, idProduct=1000, bcdDevice=11.00

10:18:31.721 [info] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3

10:18:31.721 [info] usb 1-1.4: Product: USB DISK

10:18:31.721 [info] usb 1-1.4: Manufacturer: SMI Corporation

10:18:31.721 [info] usb 1-1.4: SerialNumber: CB2YC233WUVMOC2T6FFG

10:18:31.721 [info] usb-storage 1-1.4:1.0: USB Mass Storage device detected

10:18:31.721 [info] usb-storage 1-1.4:1.0: Quirks match for vid 090c pid 1000: 400

10:18:31.722 [info] scsi host1: usb-storage 1-1.4:1.0

10:18:32.869 [info] scsi 1:0:0:0: Direct-Access     SMI      USB DISK         1100 PQ: 0 ANSI: 4

10:18:32.870 [info] sd 1:0:0:0: [sdb] 15728640 512-byte logical blocks: (8.05 GB/7.50 GiB)

10:18:32.870 [info] sd 1:0:0:0: [sdb] Write Protect is off

10:18:32.871 [debug] sd 1:0:0:0: [sdb] Mode Sense: 43 00 00 00

10:18:32.871 [info] sd 1:0:0:0: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA

10:18:32.904 [info]  sdb: sdb1

10:18:32.905 [info] sd 1:0:0:0: [sdb] Attached SCSI removable disk

10:18:32.915 [debug] [drive detector] added: sdb1

10:18:32.920 [debug] [DriveIndication] drive initialized.

10:18:33.166 [debug] [DriveIndication] drive reset.

10:18:33.166 [error] GenServer Platform.DriveDetector terminating
** (FunctionClauseError) no function clause matching in Platform.DriveDetector.handle_info/2
    (platform 0.1.2) lib/platform/drive_detector.ex:47: Platform.DriveDetector.handle_info({#Reference<0.800164087.268500994.215856>, :ok}, {#Reference<0.800164087.268435457.213446>, MapSet.new(["sda1", "sdb1"])})
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {#Reference<0.800164087.268500994.215856>, :ok}
State: {#Reference<0.800164087.268435457.213446>, MapSet.new(["sda1", "sdb1"])}

10:18:33.270 [debug] [drive detector] added: sda1, sdb1

10:18:33.270 [debug] [DriveIndication] drive initialized.

10:18:33.521 [debug] [DriveIndication] drive reset.

10:18:33.521 [error] GenServer Platform.DriveDetector terminating
** (FunctionClauseError) no function clause matching in Platform.DriveDetector.handle_info/2
    (platform 0.1.2) lib/platform/drive_detector.ex:47: Platform.DriveDetector.handle_info({#Reference<0.800164087.268500993.213482>, :ok}, {#Reference<0.800164087.268435457.213511>, MapSet.new(["sda1", "sdb1"])})
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {#Reference<0.800164087.268500993.213482>, :ok}
State: {#Reference<0.800164087.268435457.213511>, MapSet.new(["sda1", "sdb1"])}

10:18:33.626 [debug] [drive detector] added: sda1, sdb1

10:18:33.626 [debug] [DriveIndication] drive initialized.

10:18:33.762 [debug] [usb watcher] New devices found: %{"sdb" => [["sdb", "sdb1"], ["sdb"]]}

10:18:33.762 [debug] [usb watcher] Device partitions: [["sdb", "sdb1"], ["sdb"]]

10:18:33.762 [info] [usb watcher] New block device found: sdb1

10:18:33.763 [debug] [platform] [storage] new device on main : ["sdb1"]

10:18:33.763 [info] Platform.App.Media.Supervisor start

10:18:33.765 [debug] Platform.App.Media.Supervisor init result {:ok, {%{intensity: 1, period: 5, strategy: :rest_for_one}, [%{id: Platform.App.Media.TaskSupervisor, start: {Task.Supervisor, :start_link, [[name: Platform.App.Media.TaskSupervisor]]}, type: :supervisor}, %{id: Platform.App.MediaStages.DriveIndicationStarting, shutdown: 115000, start: {DynamicSupervisor, :start_link, [[name: Platform.App.MediaStages.DriveIndicationStarting, strategy: :one_for_one, max_restarts: 0]]}, type: :supervisor}, %{id: Platform.Storage.DriveIndicationStarter, shutdown: 15000, start: {Platform.Storage.DriveIndicationStarter, :start_link, [[next: [under: Platform.App.MediaStages.DriveIndicationStarting, run: [%{id: Platform.App.MediaStages.Healing, shutdown: 110000, start: {DynamicSupervisor, :start_link, [[name: Platform.App.MediaStages.Healing, strategy: :one_for_one, max_restarts: 0]]}, type: :supervisor}, {Platform.Storage.Healer, [device: "sdb1", task_in: Platform.App.Media.TaskSupervisor, next: [under: Platform.App.MediaStages.Healing, run: [%{id: Platform.App.MediaStages.Mounting, shutdown: 95000, start: {DynamicSupervisor, :start_link, [[name: Platform.App.MediaStages.Mounting, strategy: :one_for_one, max_restarts: 0]]}, type: :supervisor}, %{id: Platform.Storage.Mounter, shutdown: 15000, start: {Platform.Storage.Mounter, :start_link, [[device: "sdb1", at: "/root/media", task_in: Platform.App.Media.TaskSupervisor, next: [under: Platform.App.MediaStages.Mounting, run: [%{id: Platform.App.Media.FunctionalityDynamicSupervisor, shutdown: 90000, start: {DynamicSupervisor, :start_link, [[name: Platform.App.Media.FunctionalityDynamicSupervisor, ...]]}, type: :supervisor}, {Platform.App.Media.Decider, ["sdb1", [mounted: "/root/media", next: [under: Platform.App.Media.FunctionalityDynamicSupervisor]]]}]]]]}}]]]}]]]]}}]}}

10:18:33.768 [debug] Platform.Storage.DriveIndicationStarter is starting w/ args: [
  next: [
    under: Platform.App.MediaStages.DriveIndicationStarting,
    run: [
      %{
        id: Platform.App.MediaStages.Healing,
        shutdown: 110000,
        start: {DynamicSupervisor, :start_link,
         [
           [
             name: Platform.App.MediaStages.Healing,
             strategy: :one_for_one,
             max_restarts: 0
           ]
         ]},
        type: :supervisor
      },
      {Platform.Storage.Healer,
       [
         device: "sdb1",
         task_in: Platform.App.Media.TaskSupervisor,
         next: [
           under: Platform.App.MediaStages.Healing,
           run: [
             %{
               id: Platform.App.MediaStages.Mounting,
               shutdown: 95000,
               start: {DynamicSupervisor, :start_link,
                [
                  [
                    name: Platform.App.MediaStages.Mounting,
                    strategy: :one_for_one,
                    max_restarts: 0
                  ]
                ]},
               type: :supervisor
             },
             %{
               id: Platform.Storage.Mounter,
               shutdown: 15000,
               start: {Platform.Storage.Mounter, :start_link,
                [
                  [
                    device: "sdb1",
                    at: "/root/media",
                    task_in: Platform.App.Media.TaskSupervisor,
                    next: [
                      under: Platform.App.MediaStages.Mounting,
                      run: [
                        %{
                          id: Platform.App.Media.FunctionalityDynamicSupervisor,
                          shutdown: 90000,
                          start: {DynamicSupervisor, :start_link,
                           [
                             [
                               name: Platform.App.Media.FunctionalityDynamicSupervisor,
                               strategy: :one_for_one,
                               max_restarts: 0
                             ]
                           ]},
                          type: :supervisor
                        },
                        {Platform.App.Media.Decider,
                         [
                           "sdb1",
                           [
                             mounted: "/root/media",
                             next: [
                               under: Platform.App.Media.FunctionalityDynamicSupervisor
                             ]
                           ]
                         ]}
                      ]
                    ]
                  ]
                ]}
             }
           ]
         ]
       ]}
    ]
  ]
]

10:18:33.770 [debug] Platform.Storage.Healer is starting w/ args: [
  device: "sdb1",
  task_in: Platform.App.Media.TaskSupervisor,
  next: [
    under: Platform.App.MediaStages.Healing,
    run: [
      %{
        id: Platform.App.MediaStages.Mounting,
        shutdown: 95000,
        start: {DynamicSupervisor, :start_link,
         [
           [
             name: Platform.App.MediaStages.Mounting,
             strategy: :one_for_one,
             max_restarts: 0
           ]
         ]},
        type: :supervisor
      },
      %{
        id: Platform.Storage.Mounter,
        shutdown: 15000,
        start: {Platform.Storage.Mounter, :start_link,
         [
           [
             device: "sdb1",
             at: "/root/media",
             task_in: Platform.App.Media.TaskSupervisor,
             next: [
               under: Platform.App.MediaStages.Mounting,
               run: [
                 %{
                   id: Platform.App.Media.FunctionalityDynamicSupervisor,
                   shutdown: 90000,
                   start: {DynamicSupervisor, :start_link,
                    [
                      [
                        name: Platform.App.Media.FunctionalityDynamicSupervisor,
                        strategy: :one_for_one,
                        max_restarts: 0
                      ]
                    ]},
                   type: :supervisor
                 },
                 {Platform.App.Media.Decider,
                  [
                    "sdb1",
                    [
                      mounted: "/root/media",
                      next: [
                        under: Platform.App.Media.FunctionalityDynamicSupervisor
                      ]
                    ]
                  ]}
               ]
             ]
           ]
         ]}
      }
    ]
  ]
]

10:18:33.771 [debug] Platform.Storage.Healer started w/ state: %{
  device: "sdb1",
  next_specs: [
    %{
      id: Platform.App.MediaStages.Mounting,
      shutdown: 95000,
      start: {DynamicSupervisor, ...},
      type: :supervisor
    },
    %{id: Platform.Storage.Mounter, shutdown: 15000, start: {...}}
  ],
  next_supervisor: Platform.App.MediaStages.Healing,
  task_supervisor: Platform.App.Media.TaskSupervisor
}

10:18:33.771 [debug] Platform.Storage.DriveIndicationStarter started w/ state: :ok

10:18:33.772 [debug] [DriveIndication] drive accepted.

10:18:33.772 [debug] media supervisor start result: {:ok, #PID<0.3648.0>}

10:18:33.804 [warn] [platform] [fsck] (4) exfatprogs version : 1.1.3
ERROR: /.Spotlight-V100/Store-V2/CB6E9C23-C66B-4EC7-8898-74F071AD5B1F/shutdown_time: cluster is already allocated for the other file. truncated to 0 bytes. Truncate (y/N)? n
/dev/sdb1: checking stopped. directories 16, files 62
/dev/sdb1: files corrupted 1, files fixed 0


10:18:33.824 [warn] [platform] [fsck] (1) fsck.fat 4.2 (2021-01-31)


10:18:33.826 [info] [platform-sync] sdb1 health checked

10:18:33.828 [debug] Platform.Storage.Mounter is starting w/ args: [
  device: "sdb1",
  at: "/root/media",
  task_in: Platform.App.Media.TaskSupervisor,
  next: [
    under: Platform.App.MediaStages.Mounting,
    run: [
      %{
        id: Platform.App.Media.FunctionalityDynamicSupervisor,
        shutdown: 90000,
        start: {DynamicSupervisor, :start_link,
         [
           [
             name: Platform.App.Media.FunctionalityDynamicSupervisor,
             strategy: :one_for_one,
             max_restarts: 0
           ]
         ]},
        type: :supervisor
      },
      {Platform.App.Media.Decider,
       [
         "sdb1",
         [
           mounted: "/root/media",
           next: [under: Platform.App.Media.FunctionalityDynamicSupervisor]
         ]
       ]}
    ]
  ]
]

10:18:33.829 [debug] Platform.Storage.Mounter started w/ state: %{
  device: "sdb1",
  next_specs: [
    %{
      id: Platform.App.Media.FunctionalityDynamicSupervisor,
      shutdown: 90000,
      start: {DynamicSupervisor, ...},
      type: :supervisor
    },
    {Platform.App.Media.Decider, ["sdb1", ...]}
  ],
  next_supervisor: Platform.App.MediaStages.Mounting,
  path: "/root/media",
  task_ref: nil,
  task_supervisor: Platform.App.Media.TaskSupervisor
}

10:18:33.831 [info] [platform] Mounting /dev/sdb1 at /root/media

10:18:33.850 [warn] exFAT-fs (sdb1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.

10:18:33.877 [debug] [DriveIndication] drive reset.

10:18:33.877 [error] GenServer Platform.DriveDetector terminating
** (FunctionClauseError) no function clause matching in Platform.DriveDetector.handle_info/2
    (platform 0.1.2) lib/platform/drive_detector.ex:47: Platform.DriveDetector.handle_info({#Reference<0.800164087.268500994.216009>, :ok}, {#Reference<0.800164087.268435458.216158>, MapSet.new(["sda1", "sdb1"])})
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {#Reference<0.800164087.268500994.216009>, :ok}
State: {#Reference<0.800164087.268435458.216158>, MapSet.new(["sda1", "sdb1"])}

10:18:33.927 [info] Platform.App.Media.Decider start

10:18:33.928 [info] Platform.App.Media.Decider starting Elixir.Platform.App.Sync.CargoSyncSupervisor

10:18:33.929 [info] CargoSyncSupervisor start

10:18:34.018 [debug] [drive detector] added: sda1, sdb1

10:18:34.019 [debug] [DriveIndication] drive initialized.

10:18:34.089 [info] starting Elixir.Platform.Storage.Bouncer with opts [db: Chat.Db.CargoDb, type: "cargo_db"]

10:18:34.089 [info] [Bouncer] No DB type found. Using cargo_db as cargo_db

10:18:34.122 [debug] Platform.Storage.Backup.Starter is starting w/ args: [flag: :cargo]

10:18:34.123 [debug] Platform.Storage.Backup.Starter started w/ state: :cargo

10:18:34.127 [debug] Platform.App.Sync.Cargo.ScopeProvider is starting w/ args: [
  target: Chat.Db.CargoDb,
  next: [
    under: Platform.App.Sync.CargoScenarioStages.Ready,
    run: [
      %{
        id: Platform.App.Sync.CargoScenarioStages.Copying,
        shutdown: 38500,
        start: {DynamicSupervisor, :start_link,
         [
           [
             name: Platform.App.Sync.CargoScenarioStages.Copying,
             strategy: :one_for_one,
             max_restarts: 0
           ]
         ]},
        type: :supervisor
      },
      %{
        id: Platform.Storage.Copier,
        shutdown: 35000,
        start: {Platform.Storage.Copier, :start_link,
         [
           [
             target: Chat.Db.CargoDb,
             task_in: Platform.App.Sync.CargoSyncSupervisor.Tasks,
             get_db_keys_from: Platform.App.Sync.Cargo.ScopeProvider,
             next: [
               under: Platform.App.Sync.CargoScenarioStages.Copying,
               run: [
                 %{
                   id: Platform.App.Sync.Cargo.InitialCopyCompleter,
                   shutdown: 1000,
                   start: {Platform.App.Sync.Cargo.InitialCopyCompleter,
                    :start_link, [[]]}
                 },
                 %{
                   id: Platform.App.Sync.CargoScenarioStages.InviteAccept,
                   shutdown: 36500,
                   start: {DynamicSupervisor, :start_link,
                    [
                      [
                        name: Platform.App.Sync.CargoScenarioStages.InviteAccept,
                        strategy: :one_for_one,
                        max_restarts: 0
                      ]
                    ]},
                   type: :supervisor
                 },
                 %{
                   id: Platform.App.Sync.Cargo.InviteAcceptor,
                   shutdown: 1000,
                   start: {Platform.App.Sync.Cargo.InviteAcceptor, :start_link,
                    [
                      [
                        next: [
                          under: Platform.App.Sync.CargoScenarioStages.InviteAccept,
                          run: [
                            %{
                              id: Platform.App.Sync.CargoScenarioStages.CollectSensorsData,
                              shutdown: 35500,
                              start: {DynamicSupervisor, :start_link,
                               [
                                 [
                                   name: Platform.App.Sync.CargoScenarioStages.CollectSensorsData,
                                   strategy: :one_for_one,
                                   max_restarts: 0
                                 ]
                               ]},
                              type: :supervisor
                            },
                            %{
                              id: Platform.App.Sync.Cargo.SensorsDataCollector,
                              shutdown: 1000,
                              start: {Platform.App.Sync.Cargo.SensorsDataCollector,
                               :start_link,
                               [
                                 [
                                   get_keys_from: Platform.App.Sync.Cargo.InviteAcceptor,
                                   next: [
                                     under: Platform.App.Sync.CargoScenarioStages.CollectSensorsData,
                                     run: [
                                       %{
                                         id: Platform.App.Sync.CargoScenarioStages.FinalCopying,
                                         shutdown: 500,
                                         start: {DynamicSupervisor, ...},
                                         type: :supervisor
                                       },
                                       %{
                                         id: Platform.Storage.Copier,
                                         shutdown: 35000,
                                         start: {...}
                                       }
                                     ]
                                   ]
                                 ]
                               ]}
                            }
                          ]
                        ]
                      ]
                    ]}
                 }
               ]
             ]
           ]
         ]}
      }
    ]
  ]
]

10:18:34.128 [debug] [DriveIndication] drive refused.

10:18:34.128 [debug] Platform.App.Sync.Cargo.ScopeProvider started w/ state: {:ok, #PID<0.3690.0>}

10:18:34.129 [debug] Platform.App.Sync.Cargo.ScopeProvider terminated from :terminate w/ reason: :shutdown

10:18:34.130 [debug] Platform.Storage.Backup.Starter terminated from :terminate w/ reason: :shutdown

10:18:34.132 [debug] Media Supervisor terminating child Platform.App.MediaStages.DriveIndicationStarting

10:18:34.133 [debug] Platform.Storage.Healer terminated from :terminate w/ reason: :shutdown

10:18:34.134 [debug] Platform.Storage.Mounter terminated from :terminate w/ reason: :shutdown

10:18:34.134 [warn] mount cleanup /root/media :shutdown

10:18:34.144 [debug] Platform.App.Media.Supervisor terminates all stages

10:18:34.269 [debug] [DriveIndication] drive reset.

10:18:34.269 [error] GenServer Platform.DriveDetector terminating
** (FunctionClauseError) no function clause matching in Platform.DriveDetector.handle_info/2
    (platform 0.1.2) lib/platform/drive_detector.ex:47: Platform.DriveDetector.handle_info({#Reference<0.800164087.268500993.213773>, :ok}, {#Reference<0.800164087.268435457.213983>, MapSet.new(["sda1", "sdb1"])})
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {#Reference<0.800164087.268500993.213773>, :ok}
State: {#Reference<0.800164087.268435457.213983>, MapSet.new(["sda1", "sdb1"])}

10:18:34.273 [debug] Platform.Storage.DriveIndication terminated from :terminate w/ reason: :shutdown

10:18:34.273 [debug] [DriveIndication] drive reset. shutting down

10:18:34.276 [debug] Platform.Storage.DriveIndicationStarter terminated from :terminate w/ reason: :shutdown

10:18:34.276 [error] GenServer #PID<0.3651.0> terminating
** (UndefinedFunctionError) function Platform.Storage.DriveIndication.reset/0 is undefined or private
    (platform 0.1.2) Platform.Storage.DriveIndication.reset()
    (graceful_genserver 0.1.5) lib/functions.ex:33: GracefulGenServer.Functions.terminate/3
    (stdlib 4.1.1) gen_server.erl:1161: :gen_server.try_terminate/3
    (stdlib 4.1.1) gen_server.erl:1351: :gen_server.terminate/10
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.3648.0>, :shutdown}
State: :ok

10:18:34.281 [debug] Platform.Storage.Healer terminated from :terminate w/ reason: :shutdown

10:18:34.281 [debug] Platform.Storage.Mounter terminated from :terminate w/ reason: :shutdown

10:18:34.281 [warn] mount cleanup /root/storage :shutdown

10:18:34.289 [debug] Platform.Storage.InternalToMain.Copier terminated from :terminate w/ reason: :shutdown

10:18:34.289 [warn] copier cleanup :shutdown

10:18:34.292 [debug] [chat] Ordering reset

10:18:34.298 [debug] Platform.Storage.InternalToMain.Switcher terminated from :terminate w/ reason: :shutdown

10:18:34.299 [warn] switcher cleanup :shutdown

10:18:34.300 [debug] Platform.Storage.InternalToMain.Starter terminated from :terminate w/ reason: :shutdown

10:18:34.308 [info] Application platform exited: shutdown

10:18:42.624 [info] GET /

10:18:42.624 [debug] Processing with ChatWeb.MainLive.Index.index/2
  Parameters: %{}
  Pipelines: [:browser]

10:18:42.648 [info] Sent 200 in 24ms

10:18:42.691 [info] CONNECTED TO Phoenix.LiveView.Socket in 141Âµs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "dnQFfRVVdD0-JSwgCxcCHB8GDigrB2Ya2AuPem7nGrvLqrihxdmANf4h", "_live_referer" => "undefined", "_mounts" => "0", "_track_static" => %{"0" => "https://buckitup.app/assets/app-85643fae7a9660ef782d8c42cad88d8c.css?vsn=d", "1" => "https://buckitup.app/assets/app-49bf8cd5587f10e1f1ffb35a9a8d06f2.js?vsn=d"}, "tz_info" => %{"locale" => "en-GB", "timestamp" => "1694513984", "timezone" => "Europe/Athens", "timezone_offset" => "3"}, "vsn" => "2.0.0"}

10:18:42.701 [debug] MOUNT ChatWeb.MainLive.Index
  Parameters: %{}
  Session: %{"_csrf_token" => "D5p-p8CSyWZlzektgbcieaRr", "operating_system" => "Mac OS X"}

10:19:44.000 [info] nerves_time set system clock to 2023-09-12 10:19:44 UTC

10:19:44.001 [debug] Replied in 12ms

10:19:44.002 [debug] HANDLE PARAMS in ChatWeb.MainLive.Index
  Parameters: %{}

10:19:44.002 [debug] Replied in 246Âµs

10:19:44.008 [debug] HANDLE EVENT "local-time" in ChatWeb.MainLive.Index
  Parameters: %{"locale" => "en-GB", "timestamp" => 1694513984, "timezone" => "Europe/Athens", "timezone_offset" => 3}

10:19:44.008 [debug] Replied in 734Âµs

10:19:44.010 [debug] HANDLE EVENT "restoreAuth" in ChatWeb.MainLive.Index
  Parameters: %{"auth" => "[[\"pedro\",\"6p4IT8aJJyqElnp1R1WZYmblx3XP3uAoU3p1N1QdVskDgENhNm7I8nEQCA7+9KcxZRbz01CdNI+JDWYaWev+LzM=\"],[\"8JbSljHAelo71qsPyV+muIl7LLv/MGXyxbog0PbAtisC1hhzxF+o1LNUvakPKK/b0hx6lvYVv8UeJD6y+Jp00Y0=\",\"vQ+bUkdxFUW0pO9vdKlu1CUrqT4ZSUwvi5w5innNPJAC1V7kGPDDUkzeVany++vcdb3v87kMfcgUoFgiL6PeOb0=\",\"VFk4GfK/0BQoFlnoyZumVQMC584CRmi2SvRvk9FJNycDeGb7MGPnnmIciCVlkxy+/R5pTIYbHHIe8jsHnRNmSR0=\",\"eoVesvib6IdGlOLJthxuj5/n98NrTcq7fi+U+Xqr5awCuVhzbPXexU2aDcQOu4UIF1Ho4SHaLGD/scFJGPy5MRw=\",\"2j1jStfj5a2eTmkZTS8dW7Y9eniEiB8SUc49+XKYZuoDCWQX4nHyKcQviFrtLrypUDtCptq26Qe47UU3xJjkYC8=\",\"t9WHzC5JCbgOfHsdeEnYu30YIyusGGLCyfbiZB5Iy6UCajphDXv0c2G+hwiEL6jrrHV8vxGtbsfth/dRyOFw2UU=\",\"HOZDe6wloWP0XteNoWAN2JB+0Vkt9ZJL2567sXxGCqED+LS4chT0msd04zRVrLx4d1DeNWCnpGtVNGo5M9j22Qo=\"],[]]", "room_count" => 6}

10:19:44.016 [debug] [copying]  -> Chat.Db.InternalDb[users: <<3, 128, 67, 97, 54, 110, 200, 242, 113, 16, 8, 14, 254, 244, 167, 49, 101, 22, 243, 211, 80, 157, 52, 143, 137, 13, 102, 26, 89, 235, 254, 47, 51>>]

10:19:44.021 [debug] [copying]  -> Chat.Db.InternalDb[{:action_log, 224, <<3, 128, 67, 97, 54, 110, 200, 242, 113, 16, 8, 14, 254, 244, 167, 49, 101, 22, 243, 211, 80, 157, 52, 143, 137, 13, 102, 26, 89, 235, 254, 47, 51>>}]

10:19:44.067 [debug] Replied in 58ms

10:19:44.674 [info] GET /

10:19:44.675 [debug] Processing with ChatWeb.MainLive.Index.index/2
  Parameters: %{}
  Pipelines: [:browser]

10:19:44.698 [info] Sent 200 in 24ms

10:19:44.744 [info] CONNECTED TO Phoenix.LiveView.Socket in 146Âµs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "HEcacgMJAh8xFAgaMyAFRQBVJzMgWScKXrj_s1ALHCRvIEn1g7DZE8ux", "_live_referer" => "undefined", "_mounts" => "0", "_track_static" => %{"0" => "https://buckitup.app/assets/app-85643fae7a9660ef782d8c42cad88d8c.css?vsn=d", "1" => "https://buckitup.app/assets/app-49bf8cd5587f10e1f1ffb35a9a8d06f2.js?vsn=d"}, "tz_info" => %{"locale" => "en-GB", "timestamp" => "1694513985", "timezone" => "Europe/Athens", "timezone_offset" => "3"}, "vsn" => "2.0.0"}

10:19:44.751 [debug] MOUNT ChatWeb.MainLive.Index
  Parameters: %{}
  Session: %{"_csrf_token" => "D5p-p8CSyWZlzektgbcieaRr", "operating_system" => "Mac OS X"}

10:19:45.000 [info] nerves_time set system clock to 2023-09-12 10:19:45 UTC

10:19:45.001 [debug] Replied in 11ms

10:19:45.002 [debug] HANDLE PARAMS in ChatWeb.MainLive.Index
  Parameters: %{}

10:19:45.002 [debug] Replied in 200Âµs

10:19:45.010 [debug] HANDLE EVENT "local-time" in ChatWeb.MainLive.Index
  Parameters: %{"locale" => "en-GB", "timestamp" => 1694513985, "timezone" => "Europe/Athens", "timezone_offset" => 3}

10:19:45.011 [debug] Replied in 699Âµs

10:19:45.012 [debug] HANDLE EVENT "restoreAuth" in ChatWeb.MainLive.Index
  Parameters: %{"auth" => "[[\"pedro\",\"6p4IT8aJJyqElnp1R1WZYmblx3XP3uAoU3p1N1QdVskDgENhNm7I8nEQCA7+9KcxZRbz01CdNI+JDWYaWev+LzM=\"],[\"8JbSljHAelo71qsPyV+muIl7LLv/MGXyxbog0PbAtisC1hhzxF+o1LNUvakPKK/b0hx6lvYVv8UeJD6y+Jp00Y0=\",\"vQ+bUkdxFUW0pO9vdKlu1CUrqT4ZSUwvi5w5innNPJAC1V7kGPDDUkzeVany++vcdb3v87kMfcgUoFgiL6PeOb0=\",\"VFk4GfK/0BQoFlnoyZumVQMC584CRmi2SvRvk9FJNycDeGb7MGPnnmIciCVlkxy+/R5pTIYbHHIe8jsHnRNmSR0=\",\"eoVesvib6IdGlOLJthxuj5/n98NrTcq7fi+U+Xqr5awCuVhzbPXexU2aDcQOu4UIF1Ho4SHaLGD/scFJGPy5MRw=\",\"2j1jStfj5a2eTmkZTS8dW7Y9eniEiB8SUc49+XKYZuoDCWQX4nHyKcQviFrtLrypUDtCptq26Qe47UU3xJjkYC8=\",\"t9WHzC5JCbgOfHsdeEnYu30YIyusGGLCyfbiZB5Iy6UCajphDXv0c2G+hwiEL6jrrHV8vxGtbsfth/dRyOFw2UU=\",\"HOZDe6wloWP0XteNoWAN2JB+0Vkt9ZJL2567sXxGCqED+LS4chT0msd04zRVrLx4d1DeNWCnpGtVNGo5M9j22Qo=\"],[]]", "room_count" => 6}

10:19:45.017 [debug] [copying]  -> Chat.Db.InternalDb[users: <<3, 128, 67, 97, 54, 110, 200, 242, 113, 16, 8, 14, 254, 244, 167, 49, 101, 22, 243, 211, 80, 157, 52, 143, 137, 13, 102, 26, 89, 235, 254, 47, 51>>]

10:19:45.020 [debug] [copying]  -> Chat.Db.InternalDb[{:action_log, 225, <<3, 128, 67, 97, 54, 110, 200, 242, 113, 16, 8, 14, 254, 244, 167, 49, 101, 22, 243, 211, 80, 157, 52, 143, 137, 13, 102, 26, 89, 235, 254, 47, 51>>}]

10:19:45.053 [debug] Replied in 41ms

10:19:45.741 [debug] HANDLE EVENT "switch-lobby-mode" in ChatWeb.MainLive.Index
  Parameters: %{"lobby-mode" => "rooms", "value" => ""}

10:19:45.741 [debug] Replied in 624Âµs

10:19:46.690 [debug] HANDLE EVENT "room/switch" in ChatWeb.MainLive.Index
  Parameters: %{"room" => "026a3a610d7bf47361be8708842fa8ebac757cbf11ad6ec7ed87f751c8e170d945", "value" => 0}

10:19:46.696 [debug] [copying]  -> Chat.Db.InternalDb[{:action_log, 226, <<3, 128, 67, 97, 54, 110, 200, 242, 113, 16, 8, 14, 254, 244, 167, 49, 101, 22, 243, 211, 80, 157, 52, 143, 137, 13, 102, 26, 89, 235, 254, 47, 51>>}]

10:19:46.813 [debug] Replied in 123ms

10:19:47.607 [debug] HANDLE EVENT "room/switch" in ChatWeb.MainLive.Index
  Parameters: %{"room" => "03f8b4b87214f49ac774e33455acbc787750de3560a7a46b55346a3933d8f6d90a", "value" => 0}

10:19:47.612 [debug] [copying]  -> Chat.Db.InternalDb[{:action_log, 227, <<3, 128, 67, 97, 54, 110, 200, 242, 113, 16, 8, 14, 254, 244, 167, 49, 101, 22, 243, 211, 80, 157, 52, 143, 137, 13, 102, 26, 89, 235, 254, 47, 51>>}]

10:19:47.784 [debug] Replied in 177ms

10:19:49.665 [debug] HANDLE EVENT "room/switch" in ChatWeb.MainLive.Index
  Parameters: %{"room" => "026a3a610d7bf47361be8708842fa8ebac757cbf11ad6ec7ed87f751c8e170d945", "value" => 0}

10:19:49.670 [debug] [copying]  -> Chat.Db.InternalDb[{:action_log, 228, <<3, 128, 67, 97, 54, 110, 200, 242, 113, 16, 8, 14, 254, 244, 167, 49, 101, 22, 243, 211, 80, 157, 52, 143, 137, 13, 102, 26, 89, 235, 254, 47, 51>>}]

10:19:49.787 [debug] Replied in 121ms

123 out of 123 new messages shown.
:ok
iex(5)>
````

**Comment by sviatosluv** [comment]
this is what happens when 2 drive is being unplugged and plugged in:
````
iex(13)> RingLogger.next

10:30:29.911 [info] usb 1-1.4: USB disconnect, device number 4

10:30:29.924 [info] sd 1:0:0:0: [sdb] Synchronizing SCSI cache

10:30:29.924 [info] sd 1:0:0:0: [sdb] Synchronize Cache(10) failed: Result: hostbyte=0x01 driverbyte=DRIVER_OK

3 out of 3 new messages shown.
:ok
iex(14)> RingLogger.next

10:30:36.776 [info] usb 1-1.4: new high-speed USB device number 5 using xhci_hcd

10:30:36.891 [info] usb 1-1.4: New USB device found, idVendor=090c, idProduct=1000, bcdDevice=11.00

10:30:36.891 [info] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3

10:30:36.891 [info] usb 1-1.4: Product: USB DISK

10:30:36.891 [info] usb 1-1.4: Manufacturer: SMI Corporation

10:30:36.892 [info] usb 1-1.4: SerialNumber: CB2YC233WUVMOC2T6FFG

10:30:36.892 [info] usb-storage 1-1.4:1.0: USB Mass Storage device detected

10:30:36.892 [info] usb-storage 1-1.4:1.0: Quirks match for vid 090c pid 1000: 400

10:30:36.892 [info] scsi host1: usb-storage 1-1.4:1.0

10:30:38.067 [info] scsi 1:0:0:0: Direct-Access     SMI      USB DISK         1100 PQ: 0 ANSI: 4

10:30:38.076 [info] sd 1:0:0:0: [sdb] 15728640 512-byte logical blocks: (8.05 GB/7.50 GiB)

10:30:38.076 [info] sd 1:0:0:0: [sdb] Write Protect is off

10:30:38.076 [debug] sd 1:0:0:0: [sdb] Mode Sense: 43 00 00 00

10:30:38.077 [info] sd 1:0:0:0: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA

10:30:38.110 [info]  sdb: sdb1

10:30:38.110 [info] sd 1:0:0:0: [sdb] Attached SCSI removable disk

16 out of 16 new messages shown.
:ok
iex(15)>
````
