### ISSUE TITLE
Indicate HW problems w/ devices

### ISSUE THREAD

**Issue by sergey-lukianov** [Buckitup-chat/chat#518]
Like main struggling to write into bad sectors or remount

```
2023-09-21 15:12:47.544000 [info] [platform] Mounting /dev/sdc1 at /root/storage
2023-09-21 15:12:47.557000 [error] /dev/sdc1: Can't open blockdev
2023-09-21 15:12:47.557000 [error] /dev/sdc1: Can't open blockdev
2023-09-21 15:12:47.557000 [error] Task #PID<0.4487.0> started from #PID<0.4486.0> terminating
** (MatchError) no match of right hand side value: {"", 255}
    (platform 0.1.2) lib/platform/storage/device.ex:23: Platform.Storage.Device.mount_on/2
    (elixir 1.14.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<1.89489099/0 in Platform.Storage.Mounter.on_msg/2>
    Args: []
2023-09-21 15:12:47.562000 [debug] Platform.Storage.Mounter terminated from :terminate w/ reason: {:function_clause,
 [
   {Platform.Storage.Mounter, :on_msg,
    [
      {:DOWN, #Reference<0.690524194.269287425.12044>, :process, #PID<0.4487.0>,
       {{:badmatch, {"", 255}},
        [
          {Platform.Storage.Device, :mount_on, 2,
           [file: 'lib/platform/storage/device.ex', line: 23]},
          {Task.Supervised, :invoke_mfa, 2,
           [file: 'lib/task/supervised.ex', line: 89]},
          {Task.Supervised, :reply, 4,
           [file: 'lib/task/supervised.ex', line: 34]},
          {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}
        ]}},
      %{
        device: "sdc1",
        next_specs: [
          %{
            id: Chat.Db.MainDbSupervisor,
            shutdown: 20000,
            start: {Chat.Db.MainDbSupervisor, :start_link,
             ["/root/storage/main_db/v.9"]},
            type: :supervisor
          },
          {Platform.Storage.Bouncer, [db: Chat.Db.MainDb, type: "main_db"]},
          %{
            id: Platform.Storage.InternalToMain.Starter,
            shutdown: 1000,
            start: {Platform.Storage.InternalToMain.Starter, :start_link, [[]]}
          },
          %{
            id: Platform.App.MainStages.Copying,
            shutdown: 6000,
            start: {DynamicSupervisor, :start_link,
             [
               [
                 name: Platform.App.MainStages.Copying,
                 strategy: :one_for_one,
                 max_restarts: 0
               ]
             ]},
            type: :supervisor
          },
          %{
            id: Platform.Storage.InternalToMain.Copier,
            shutdown: 25000,
            start: {Platform.Storage.InternalToMain.Copier, :start_link,
             [
               [
                 task_in: Platform.App.Db.MainDbSupervisor.Tasks,
                 next: [
                   under: Platform.App.MainStages.Copying,
                   run: [
                     Platform.Storage.MainReplicator,
                     %{
                       id: Platform.Storage.InternalToMain.Switcher,
                       shutdown: 1000,
                       start: {Platform.Storage.InternalToMain.Switcher,
                        :start_link, [[]]}
                     }
                   ]
                 ]
               ]
             ]}
          }
        ],
        next_supervisor: Platform.App.MainStages.Mounting,
        path: "/root/storage",
        task_ref: #Reference<0.690524194.269287425.12044>,
        task_supervisor: Platform.App.Db.MainDbSupervisor.Tasks
      }
    ], [file: 'lib/platform/storage/mounter.ex', line: 28]},
   {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 1123]},
   {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 1200]},
   {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}
 ]}
2023-09-21 15:12:47.564000 [warn] mount cleanup /root/storage {:function_clause, [{Platform.Storage.Mounter, :on_msg, [{:DOWN, #Reference<0.690524194.269287425.12044>, :process, #PID<0.4487.0>, {{:badmatch, {"", 255}}, [{Platform.Storage.Device, :mount_on, 2, [file: 'lib/platform/storage/device.ex', line: 23]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 4, [file: 'lib/task/supervised.ex', line: 34]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}, %{device: "sdc1", next_specs: [%{id: Chat.Db.MainDbSupervisor, shutdown: 20000, start: {Chat.Db.MainDbSupervisor, :start_link, ["/root/storage/main_db/v.9"]}, type: :supervisor}, {Platform.Storage.Bouncer, [db: Chat.Db.MainDb, type: "main_db"]}, %{id: Platform.Storage.InternalToMain.Starter, shutdown: 1000, start: {Platform.Storage.InternalToMain.Starter, :start_link, [[]]}}, %{id: Platform.App.MainStages.Copying, shutdown: 6000, start: {DynamicSupervisor, :start_link, [[name: Platform.App.MainStages.Copying, strategy: :one_for_one, max_restarts: 0]]}, type: :supervisor}, %{id: Platform.Storage.InternalToMain.Copier, shutdown: 25000, start: {Platform.Storage.InternalToMain.Copier, :start_link, [[task_in: Platform.App.Db.MainDbSupervisor.Tasks, next: [under: Platform.App.MainStages.Copying, run: [Platform.Storage.MainReplicator, %{id: Platform.Storage.InternalToMain.Switcher, shutdown: 1000, start: {Platform.Storage.InternalToMain.Switcher, :start_link, [[]]}}]]]]}}], next_supervisor: Platform.App.MainStages.Mounting, path: "/root/storage", task_ref: #Reference<0.690524194.269287425.12044>, task_supervisor: Platform.App.Db.MainDbSupervisor.Tasks}], [file: 'lib/platform/storage/mounter.ex', line: 28]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 1123]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 1200]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}
2023-09-21 15:12:47.570000 [error] GenServer #PID<0.4486.0> terminating
** (FunctionClauseError) no function clause matching in Platform.Storage.Mounter.on_msg/2
    (platform 0.1.2) lib/platform/storage/mounter.ex:28: Platform.Storage.Mounter.on_msg({:DOWN, #Reference<0.690524194.269287425.12044>, :process, #PID<0.4487.0>, {{:badmatch, {"", 255}}, [{Platform.Storage.Device, :mount_on, 2, [file: 'lib/platform/storage/device.ex', line: 23]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 4, [file: 'lib/task/supervised.ex', line: 34]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}, %{device: "sdc1", next_specs: [%{id: Chat.Db.MainDbSupervisor, shutdown: 20000, start: {Chat.Db.MainDbSupervisor, :start_link, ["/root/storage/main_db/v.9"]}, type: :supervisor}, {Platform.Storage.Bouncer, [db: Chat.Db.MainDb, type: "main_db"]}, %{id: Platform.Storage.InternalToMain.Starter, shutdown: 1000, start: {Platform.Storage.InternalToMain.Starter, :start_link, [[]]}}, %{id: Platform.App.MainStages.Copying, shutdown: 6000, start: {DynamicSupervisor, :start_link, [[name: Platform.App.MainStages.Copying, strategy: :one_for_one, max_restarts: 0]]}, type: :supervisor}, %{id: Platform.Storage.InternalToMain.Copier, shutdown: 25000, start: {Platform.Storage.InternalToMain.Copier, :start_link, [[task_in: Platform.App.Db.MainDbSupervisor.Tasks, next: [under: Platform.App.MainStages.Copying, run: [Platform.Storage.MainReplicator, %{id: Platform.Storage.InternalToMain.Switcher, shutdown: 1000, start: {Platform.Storage.InternalToMain.Switcher, :start_link, [[]]}}]]]]}}], next_supervisor: Platform.App.MainStages.Mounting, path: "/root/storage", task_ref: #Reference<0.690524194.269287425.12044>, task_supervisor: Platform.App.Db.MainDbSupervisor.Tasks})
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.690524194.269287425.12044>, :process, #PID<0.4487.0>, {{:badmatch, {"", 255}}, [{Platform.Storage.Device, :mount_on, 2, [file: 'lib/platform/storage/device.ex', line: 23]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 4, [file: 'lib/task/supervised.ex', line: 34]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
State: %{device: "sdc1", next_specs: [%{id: Chat.Db.MainDbSupervisor, shutdown: 20000, start: {Chat.Db.MainDbSupervisor, :start_link, ["/root/storage/main_db/v.9"]}, type: :supervisor}, {Platform.Storage.Bouncer, [db: Chat.Db.MainDb, type: "main_db"]}, %{id: Platform.Storage.InternalToMain.Starter, shutdown: 1000, start: {Platform.Storage.InternalToMain.Starter, :start_link, [[]]}}, %{id: Platform.App.MainStages.Copying, shutdown: 6000, start: {DynamicSupervisor, :start_link, [[name: Platform.App.MainStages.Copying, strategy: :one_for_one, max_restarts: 0]]}, type: :supervisor}, %{id: Platform.Storage.InternalToMain.Copier, shutdown: 25000, start: {Platform.Storage.InternalToMain.Copier, :start_link, [[task_in: Platform.App.Db.MainDbSupervisor.Tasks, next: [under: Platform.App.MainStages.Copying, run: [Platform.Storage.MainReplicator, %{id: Platform.Storage.InternalToMain.Switcher, shutdown: 1000, start: {Platform.Storage.InternalToMain.Switcher, :start_link, [[]]}}]]]]}}], next_supervisor: Platform.App.MainStages.Mounting, path: "/root/storage", task_ref: #Reference<0.690524194.269287425.12044>, task_supervisor: Platform.App.Db.MainDbSupervisor.Tasks}
2023-09-21 15:12:47.577000 [debug] Platform.Storage.Healer terminated from :terminate w/ reason: :shutdown
2023-09-21 15:12:47.578000 [debug] Main Db Supervisor start
2023-09-21 15:12:47.578000 [debug] MainDbSupervisor exit time 87000
2023-09-21 15:12:47.580000 [debug] Platform.Storage.Healer is starting w/ args: [
  device: "sdc1",
  task_in: Platform.App.Db.MainDbSupervisor.Tasks,
  next: [
    under: Platform.App.MainStages.Healing,
    run: [
      %{
        id: Platform.App.MainStages.Mounting,
        shutdown: 57000,
        start: {DynamicSupervisor, :start_link,
         [
           [
             name: Platform.App.MainStages.Mounting,
             strategy: :one_for_one,
             max_restarts: 0
           ]
         ]},
        type: :supervisor
      },
      %{
        id: Platform.Storage.Mounter,
        shutdown: 15000,
        start: {Platform.Storage.Mounter, :start_link,
         [
           [
             device: "sdc1",
             at: "/root/storage",
             task_in: Platform.App.Db.MainDbSupervisor.Tasks,
             ...
           ]
         ]}
      }
    ]
  ]
]
2023-09-21 15:12:47.580000 [debug] Platform.Storage.Healer started w/ state: %{
  device: "sdc1",
  next_specs: [
    %{
      id: Platform.App.MainStages.Mounting,
      shutdown: 57000,
      start: {DynamicSupervisor, ...},
      type: :supervisor
    },
    %{id: Platform.Storage.Mounter, shutdown: 15000, start: {...}}
  ],
  next_supervisor: Platform.App.MainStages.Healing,
  task_supervisor: Platform.App.Db.MainDbSupervisor.Tasks
}
2023-09-21 15:12:47.586000 [warn] [platform] [fsck] (8) exfatprogs version : 1.1.3

2023-09-21 15:12:47.590000 [warn] [platform] [fsck] (6) fsck.fat 4.2 (2021-01-31)

2023-09-21 15:12:47.752000 [info] [platform-sync] sdc1 health checked
2023-09-21 15:12:47.754000 [debug] Platform.Storage.Mounter is starting w/ args: [
  device: "sdc1",
  at: "/root/storage",
  task_in: Platform.App.Db.MainDbSupervisor.Tasks,
  next: [
    under: Platform.App.MainStages.Mounting,
    run: [
      %{
        id: Chat.Db.MainDbSupervisor,
        shutdown: 20000,
        start: {Chat.Db.MainDbSupervisor, :start_link,
         ["/root/storage/main_db/v.9"]},
        type: :supervisor
      },
      {Platform.Storage.Bouncer, [db: Chat.Db.MainDb, type: "main_db"]},
      %{
        id: Platform.Storage.InternalToMain.Starter,
        shutdown: 1000,
        start: {Platform.Storage.InternalToMain.Starter, :start_link, [[]]}
      },
      %{
        id: Platform.App.MainStages.Copying,
        shutdown: 6000,
        start: {DynamicSupervisor, :start_link, [[...]]},
        type: :supervisor
      },
      %{
        id: Platform.Storage.InternalToMain.Copier,
        shutdown: 25000,
        start: {Platform.Storage.InternalToMain.Copier, :start_link, [...]}
      }
    ]
  ]
]
2023-09-21 15:12:47.755000 [debug] Platform.Storage.Mounter started w/ state: %{
  device: "sdc1",
  next_specs: [
    %{
      id: Chat.Db.MainDbSupervisor,
      shutdown: 20000,
      start: {Chat.Db.MainDbSupervisor, ...},
      type: :supervisor
    },
    {Platform.Storage.Bouncer, [db: Chat.Db.MainDb, ...]},
    %{id: Platform.Storage.InternalToMain.Starter, shutdown: 1000, ...},
    %{id: Platform.App.MainStages.Copying, ...},
    %{...}
  ],
  next_supervisor: Platform.App.MainStages.Mounting,
  path: "/root/storage",
  task_ref: nil,
  task_supervisor: Platform.App.Db.MainDbSupervisor.Tasks
}
2023-09-21 15:12:47.755000 [info] [platform] Mounting /dev/sdc1 at /root/storage
2023-09-21 15:12:47.768000 [error] /dev/sdc1: Can't open blockdev
2023-09-21 15:12:47.769000 [error] /dev/sdc1: Can't open blockdev
2023-09-21 15:12:47.769000 [error] Task #PID<0.4503.0> started from #PID<0.4502.0> terminating
** (MatchError) no match of right hand side value: {"", 255}
    (platform 0.1.2) lib/platform/storage/device.ex:23: Platform.Storage.Device.mount_on/2
    (elixir 1.14.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<1.89489099/0 in Platform.Storage.Mounter.on_msg/2>
    Args: []
2023-09-21 15:12:47.775000 [debug] Platform.Storage.Mounter terminated from :terminate w/ reason: {:function_clause,
 [
   {Platform.Storage.Mounter, :on_msg,
    [
      {:DOWN, #Reference<0.690524194.268763139.235093>, :process,
       #PID<0.4503.0>,
       {{:badmatch, {"", 255}},
        [
          {Platform.Storage.Device, :mount_on, 2,
           [file: 'lib/platform/storage/device.ex', line: 23]},
          {Task.Supervised, :invoke_mfa, 2,
           [file: 'lib/task/supervised.ex', line: 89]},
          {Task.Supervised, :reply, 4,
           [file: 'lib/task/supervised.ex', line: 34]},
          {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}
        ]}},
      %{
        device: "sdc1",
        next_specs: [
          %{
            id: Chat.Db.MainDbSupervisor,
            shutdown: 20000,
            start: {Chat.Db.MainDbSupervisor, :start_link,
             ["/root/storage/main_db/v.9"]},
            type: :supervisor
          },
          {Platform.Storage.Bouncer, [db: Chat.Db.MainDb, type: "main_db"]},
          %{
            id: Platform.Storage.InternalToMain.Starter,
            shutdown: 1000,
            start: {Platform.Storage.InternalToMain.Starter, :start_link, [[]]}
          },
          %{
            id: Platform.App.MainStages.Copying,
            shutdown: 6000,
            start: {DynamicSupervisor, :start_link,
             [
               [
                 name: Platform.App.MainStages.Copying,
                 strategy: :one_for_one,
                 max_restarts: 0
               ]
             ]},
            type: :supervisor
          },
          %{
            id: Platform.Storage.InternalToMain.Copier,
            shutdown: 25000,
            start: {Platform.Storage.InternalToMain.Copier, :start_link,
             [
               [
                 task_in: Platform.App.Db.MainDbSupervisor.Tasks,
                 next: [
                   under: Platform.App.MainStages.Copying,
                   run: [
                     Platform.Storage.MainReplicator,
                     %{
                       id: Platform.Storage.InternalToMain.Switcher,
                       shutdown: 1000,
                       start: {Platform.Storage.InternalToMain.Switcher,
                        :start_link, [[]]}
                     }
                   ]
                 ]
               ]
             ]}
          }
        ],
        next_supervisor: Platform.App.MainStages.Mounting,
        path: "/root/storage",
        task_ref: #Reference<0.690524194.268763139.235093>,
        task_supervisor: Platform.App.Db.MainDbSupervisor.Tasks
      }
    ], [file: 'lib/platform/storage/mounter.ex', line: 28]},
   {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 1123]},
   {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 1200]},
   {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}
 ]}
2023-09-21 15:12:47.777000 [warn] mount cleanup /root/storage {:function_clause, [{Platform.Storage.Mounter, :on_msg, [{:DOWN, #Reference<0.690524194.268763139.235093>, :process, #PID<0.4503.0>, {{:badmatch, {"", 255}}, [{Platform.Storage.Device, :mount_on, 2, [file: 'lib/platform/storage/device.ex', line: 23]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 4, [file: 'lib/task/supervised.ex', line: 34]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}, %{device: "sdc1", next_specs: [%{id: Chat.Db.MainDbSupervisor, shutdown: 20000, start: {Chat.Db.MainDbSupervisor, :start_link, ["/root/storage/main_db/v.9"]}, type: :supervisor}, {Platform.Storage.Bouncer, [db: Chat.Db.MainDb, type: "main_db"]}, %{id: Platform.Storage.InternalToMain.Starter, shutdown: 1000, start: {Platform.Storage.InternalToMain.Starter, :start_link, [[]]}}, %{id: Platform.App.MainStages.Copying, shutdown: 6000, start: {DynamicSupervisor, :start_link, [[name: Platform.App.MainStages.Copying, strategy: :one_for_one, max_restarts: 0]]}, type: :supervisor}, %{id: Platform.Storage.InternalToMain.Copier, shutdown: 25000, start: {Platform.Storage.InternalToMain.Copier, :start_link, [[task_in: Platform.App.Db.MainDbSupervisor.Tasks, next: [under: Platform.App.MainStages.Copying, run: [Platform.Storage.MainReplicator, %{id: Platform.Storage.InternalToMain.Switcher, shutdown: 1000, start: {Platform.Storage.InternalToMain.Switcher, :start_link, [[]]}}]]]]}}], next_supervisor: Platform.App.MainStages.Mounting, path: "/root/storage", task_ref: #Reference<0.690524194.268763139.235093>, task_supervisor: Platform.App.Db.MainDbSupervisor.Tasks}], [file: 'lib/platform/storage/mounter.ex', line: 28]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 1123]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 1200]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}
2023-09-21 15:12:47.783000 [error] GenServer #PID<0.4502.0> terminating
** (FunctionClauseError) no function clause matching in Platform.Storage.Mounter.on_msg/2
    (platform 0.1.2) lib/platform/storage/mounter.ex:28: Platform.Storage.Mounter.on_msg({:DOWN, #Reference<0.690524194.268763139.235093>, :process, #PID<0.4503.0>, {{:badmatch, {"", 255}}, [{Platform.Storage.Device, :mount_on, 2, [file: 'lib/platform/storage/device.ex', line: 23]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 4, [file: 'lib/task/supervised.ex', line: 34]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}, %{device: "sdc1", next_specs: [%{id: Chat.Db.MainDbSupervisor, shutdown: 20000, start: {Chat.Db.MainDbSupervisor, :start_link, ["/root/storage/main_db/v.9"]}, type: :supervisor}, {Platform.Storage.Bouncer, [db: Chat.Db.MainDb, type: "main_db"]}, %{id: Platform.Storage.InternalToMain.Starter, shutdown: 1000, start: {Platform.Storage.InternalToMain.Starter, :start_link, [[]]}}, %{id: Platform.App.MainStages.Copying, shutdown: 6000, start: {DynamicSupervisor, :start_link, [[name: Platform.App.MainStages.Copying, strategy: :one_for_one, max_restarts: 0]]}, type: :supervisor}, %{id: Platform.Storage.InternalToMain.Copier, shutdown: 25000, start: {Platform.Storage.InternalToMain.Copier, :start_link, [[task_in: Platform.App.Db.MainDbSupervisor.Tasks, next: [under: Platform.App.MainStages.Copying, run: [Platform.Storage.MainReplicator, %{id: Platform.Storage.InternalToMain.Switcher, shutdown: 1000, start: {Platform.Storage.InternalToMain.Switcher, :start_link, [[]]}}]]]]}}], next_supervisor: Platform.App.MainStages.Mounting, path: "/root/storage", task_ref: #Reference<0.690524194.268763139.235093>, task_supervisor: Platform.App.Db.MainDbSupervisor.Tasks})
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.690524194.268763139.235093>, :process, #PID<0.4503.0>, {{:badmatch, {"", 255}}, [{Platform.Storage.Device, :mount_on, 2, [file: 'lib/platform/storage/device.ex', line: 23]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 4, [file: 'lib/task/supervised.ex', line: 34]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
State: %{device: "sdc1", next_specs: [%{id: Chat.Db.MainDbSupervisor, shutdown: 20000, start: {Chat.Db.MainDbSupervisor, :start_link, ["/root/storage/main_db/v.9"]}, type: :supervisor}, {Platform.Storage.Bouncer, [db: Chat.Db.MainDb, type: "main_db"]}, %{id: Platform.Storage.InternalToMain.Starter, shutdown: 1000, start: {Platform.Storage.InternalToMain.Starter, :start_link, [[]]}}, %{id: Platform.App.MainStages.Copying, shutdown: 6000, start: {DynamicSupervisor, :start_link, [[name: Platform.App.MainStages.Copying, strategy: :one_for_one, max_restarts: 0]]}, type: :supervisor}, %{id: Platform.Storage.InternalToMain.Copier, shutdown: 25000, start: {Platform.Storage.InternalToMain.Copier, :start_link, [[task_in: Platform.App.Db.MainDbSupervisor.Tasks, next: [under: Platform.App.MainStages.Copying, run: [Platform.Storage.MainReplicator, %{id: Platform.Storage.InternalToMain.Switcher, shutdown: 1000, start: {Platform.Storage.InternalToMain.Switcher, :start_link, [[]]}}]]]]}}], next_supervisor: Platform.App.MainStages.Mounting, path: "/root/storage", task_ref: #Reference<0.690524194.268763139.235093>, task_supervisor: Platform.App.Db.MainDbSupervisor.Tasks}
```

**Comment by buckitupnet** [comment]
Make indication in form of the sync icon rapid blinking red.
