### ISSUE TITLE
Check message reading error

### ISSUE THREAD

**Issue by sergey-lukianov** [Buckitup-chat/chat#534]
```
2023-09-27 07:10:02.708000 [error] GenServer #PID<0.4273.0> terminating
** (FunctionClauseError) no function clause matching in Chat.Rooms.RoomMessages.read/4
    (chat 0.1.0) lib/chat/rooms/room_messages.ex:41: Chat.Rooms.RoomMessages.read(nil, nil, {nil, 0}, 16)
    (chat 0.1.0) lib/chat_web/live/main_live/page/room.ex:170: ChatWeb.MainLive.Page.Room.load_new_messages/1
    (chat 0.1.0) lib/chat_web/live/main_live/index.ex:457: ChatWeb.MainLive.Index.handle_info/2
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/channel.ex:276: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:room, :load_new_messages}
```

**Comment by sergey-lukianov** [comment]
fixed  already
