### ISSUE TITLE
Unable to recover connection

### ISSUE THREAD

**Issue by sergey-lukianov** [Buckitup-chat/chat#538]
If state is lost (device reboot), connection recovery does not triggers login

This should be done with a plug

**Comment by sergey-lukianov** [comment]
```
[error] GenServer #PID<0.650.0> terminating
** (FunctionClauseError) no function clause matching in ChatWeb.MainLive.Page.Lobby.assign_user_list/2
    (chat 0.1.0) lib/chat_web/live/main_live/page/lobby.ex:248: ChatWeb.MainLive.Page.Lobby.assign_user_list(#Phoenix.LiveView.Socket<id: "phx-F6wEQIlsYcQP-Q3B", endpoint: ChatWeb.Endpoint, view: ChatWeb.MainLive.Index, parent_pid: nil, root_pid: #PID<0.650.0>, router: ChatWeb.Router, assigns: %{mode: :user_list, backup_settings: %Chat.Admin.BackupSettings{type: :regular}, cargo_settings: %Chat.Admin.CargoSettings{checkpoints: [], camera_sensors: [""], weight_sensor: %{type: "NCI", parity: :none}}, media_settings: %Chat.Admin.MediaSettings{functionality: :backup, main: true}, handshaked: false, live_action: :index, need_login: true, monotonic_offset: 2282203784, usb_drive_dump_room: nil, cargo_room: nil, operating_system: "Mac OS X", __changed__: %{search_filter: true}, uploads_metadata: %{}, uploads: %{file: #Phoenix.LiveView.UploadConfig<name: :file, max_entries: 2000, max_file_size: 102400000000, entries: [], accept: :any, ref: "phx-F6wETd7MMv_HgwAC", errors: [], auto_upload?: true, progress_event: &ChatWeb.LiveHelpers.Uploader.handle_progress/3, writer: #Function<1.79914505/3 in Phoenix.LiveView.UploadConfig.build/3>, ...>, my_keys_file: #Phoenix.LiveView.UploadConfig<name: :my_keys_file, max_entries: 1, max_file_size: 1024000000, entries: [], accept: :any, ref: "phx-F6wETd_Iw1zHgwBC", errors: [], auto_upload?: true, progress_event: #Function<1.106052604/3 in ChatWeb.MainLive.Index.handle_progress>, writer: #Function<1.79914505/3 in Phoenix.LiveView.UploadConfig.build/3>, ...>, recovery_keys: #Phoenix.LiveView.UploadConfig<name: :recovery_keys, max_entries: 100, max_file_size: 8000000, entries: [], accept: ".social_part", ref: "phx-F6wETd_JdWrHgwCC", errors: [], auto_upload?: true, progress_event: &ChatWeb.MainLive.Page.RecoverKeyShare.handle_progress/3, writer: #Function<1.79914505/3 in Phoenix.LiveView.UploadConfig.build/3>, ...>, __phoenix_refs_to_names__: %{"phx-F6wETd7MMv_HgwAC" => :file, "phx-F6wETd_Iw1zHgwBC" => :my_keys_file, "phx-F6wETd_JdWrHgwCC" => :recovery_keys}}, file_uploads_order: [], timezone: "Europe/Kiev", live_modal: nil, flash: %{}, locale: "en-GB", timezone_offset: 2, search_filter: :on}, transport_pid: #PID<0.639.0>, ...>, "")
    (chat 0.1.0) lib/chat_web/live/main_live/index.ex:325: ChatWeb.MainLive.Index.handle_event/3
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:487: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.2.1) /Users/lukianov/work/buckitUp/chat/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:246: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 5.1.1) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.1.1) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F6wEQIlsYcQP-Q3B", event: "event", payload: %{"event" => "lobby/search", "type" => "form", "uploads" => %{}, "value" => "dialog%5Bname%5D=&_target=dialog%5Bname%5D"}, ref: "13", join_ref: "12"}
State: %{socket: #Phoenix.LiveView.Socket<id: "phx-F6wEQIlsYcQP-Q3B", endpoint: ChatWeb.Endpoint, view: ChatWeb.MainLive.Index, parent_pid: nil, root_pid: #PID<0.650.0>, router: ChatWeb.Router, assigns: %{mode: :user_list, backup_settings: %Chat.Admin.BackupSettings{type: :regular}, cargo_settings: %Chat.Admin.CargoSettings{checkpoints: [], camera_sensors: [""], weight_sensor: %{type: "NCI", parity: :none}}, media_settings: %Chat.Admin.MediaSettings{functionality: :backup, main: true}, handshaked: false, live_action: :index, need_login: true, monotonic_offset: 2282203784, usb_drive_dump_room: nil, cargo_room: nil, operating_system: "Mac OS X", __changed__: %{}, uploads_metadata: %{}, uploads: %{file: #Phoenix.LiveView.UploadConfig<name: :file, max_entries: 2000, max_file_size: 102400000000, entries: [], accept: :any, ref: "phx-F6wETd7MMv_HgwAC", errors: [], auto_upload?: true, progress_event: &ChatWeb.LiveHelpers.Uploader.handle_progress/3, writer: #Function<1.79914505/3 in Phoenix.LiveView.UploadConfig.build/3>, ...>, my_keys_file: #Phoenix.LiveView.UploadConfig<name: :my_keys_file, max_entries: 1, max_file_size: 1024000000, entries: [], accept: :any, ref: "phx-F6wETd_Iw1zHgwBC", errors: [], auto_upload?: true, progress_event: #Function<1.106052604/3 in ChatWeb.MainLive.Index.handle_progress>, writer: #Function<1.79914505/3 in Phoenix.LiveView.UploadConfig.build/3>, ...>, recovery_keys: #Phoenix.LiveView.UploadConfig<name: :recovery_keys, max_entries: 100, max_file_size: 8000000, entries: [], accept: ".social_part", ref: "phx-F6wETd_JdWrHgwCC", errors: [], auto_upload?: true, progress_event: &ChatWeb.MainLive.Page.RecoverKeyShare.handle_progress/3, writer: #Function<1.79914505/3 in Phoenix.LiveView.UploadConfig.build/3>, ...>, __phoenix_refs_to_names__: %{"phx-F6wETd7MMv_HgwAC" => :file, "phx-F6wETd_Iw1zHgwBC" => :my_keys_file, "phx-F6wETd_JdWrHgwCC" => :recovery_keys}}, file_uploads_order: [], timezone: "Europe/Kiev", live_modal: nil, flash: %{}, locale: "en-GB", timezone_offset: 2}, transport_pid: #PID<0.639.0>, ...>, components: {%{}, %{}, 1}, topic: "lv:phx-F6wEQIlsYcQP-Q3B", serializer: Phoenix.Socket.V2.JSONSerializer, join_ref: "12", upload_names: %{}, upload_pids: %{}}
Done in 731ms.
```
