### ISSUE TITLE
Writer termination

### ISSUE THREAD

**Issue by sergey-lukianov** [Buckitup-chat/chat#590]
Check why DB writer terminated

```
2024-01-20 10:07:27.994000 [error] GenServer Chat.Db.InternalDb.Writer terminating
** (stop) exited in: GenServer.call(Chat.Db.InternalDb.Queue, :demand, 5000)
    ** (EXIT) time out
    (elixir 1.15.5) lib/gen_server.ex:1074: GenServer.call/3
    (chat 0.1.0) lib/chat/db/pipeline/writer.ex:40: Chat.Db.Pipeline.Writer.demand_queue/1
    (chat 0.1.0) lib/chat/db/pipeline/writer_process.ex:45: Chat.Db.Pipeline.WriterProcess.handle_continue/2
    (stdlib 5.1.1) gen_server.erl:1067: :gen_server.try_handle_continue/3
    (stdlib 5.1.1) gen_server.erl:977: :gen_server.loop/7
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:continue, :demand}
State: {:w_state, Chat.Db.InternalDb, "/root/db/v.9_files", Chat.Db.InternalDb.Queue, Chat.Db.InternalDb.Compactor, 4, #Reference<0.3431396669.268959745.104196>}
2024-01-20 10:07:29.572000 [debug] [copying]  -> Chat.Db.MainDb[{:room_invite, "1cdc690c-ccf1-4f2c-a656-f94b2f727a65"}, {:file_index, <<2, 209, 236, 69, 93, 175, 227, 238, 199, 221, 196, 81, 10, 209, 21, 198, 63, 116, 118, 116, 14, 178, 177, 223, 223, 210, 161, 33, 29, 97, 9, 16, 51>>, <<234, 115, 90, 251, 74, 254, 116, 32, 55, 237, 156, 225, 40, 56, 207, 254, 178, 76, 191, 237, 141, 60, 230, 16, 227, 24, 98, 10, 175, 195, 59, 134>>, "e73eb849-3249-47b9-992e-0cea49ae4cb9"}, {:room_invite_index, <<2, 79, 30, 149, 167, 63, 115, 166, 255, 111, 48, 96, 50, 207, 7, 55, 94, 115, 84, 152, 103, 167, 190, 158, 49, 59, 240, 178, 172, 1, 43, 225, 55>>, "df2a68ba-ab4e-4770-a0fa-a39614213d2d"}, {:chunk_key, {:file_chunk, <<119, 240, 208, 212, 51, 198, 148, 86, 74, 13, 122, 86, 233, 81, 162, 252, 65, 42, 137, 214, 69, 228, 148, 217, 201, 29, 115, 134, 0, 176, 164, 155>>, 0, 114585}}]
2024-01-20 10:07:32.999000 [error] GenServer Chat.Db.InternalDb.Writer terminating
** (stop) exited in: GenServer.call(Chat.Db.InternalDb.Queue, :demand, 5000)
    ** (EXIT) time out
    (elixir 1.15.5) lib/gen_server.ex:1074: GenServer.call/3
    (chat 0.1.0) lib/chat/db/pipeline/writer.ex:40: Chat.Db.Pipeline.Writer.demand_queue/1
    (chat 0.1.0) lib/chat/db/pipeline/writer_process.ex:45: Chat.Db.Pipeline.WriterProcess.handle_continue/2
    (stdlib 5.1.1) gen_server.erl:1067: :gen_server.try_handle_continue/3
    (stdlib 5.1.1) gen_server.erl:977: :gen_server.loop/7
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:continue, :demand}
State: {:w_state, Chat.Db.InternalDb, "/root/db/v.9_files", Chat.Db.InternalDb.Queue, Chat.Db.InternalDb.Compactor, 0, nil}
2024-01-20 10:07:36.146000 [debug] [copying]  -> Chat.Db.MainDb[dialogs: <<128, 7, 155, 168, 82, 233, 137, 234, 101, 156, 101, 66, 178, 221, 92, 136, 97, 235, 80, 194, 162, 43, 224, 69, 28, 254, 154, 127, 110, 90, 190, 169>>, rooms: <<3, 16, 187, 74, 215, 89, 217, 107, 52, 215, 182, 142, 21, 165, 101, 209, 81, 25, 57, 177, 149, 208, 62, 149, 220, 41, 152, 190, 115, 50, 255, 182, 248>>, chunk_key: {:file_chunk, <<195, 148, 68, 202, 104, 164, 81, 66, 23, 126, 114, 111, 145, 47, 248, 121, 81, 28, 160, 10, 149, 171, 176, 122, 139, 26, 93, 35, 31, 117, 180, 54>>, 346030080, 356515839}]
2024-01-20 10:07:38.011000 [error] GenServer Chat.Db.InternalDb.Writer terminating
** (stop) exited in: GenServer.call(Chat.Db.InternalDb.Queue, :demand, 5000)
    ** (EXIT) time out
    (elixir 1.15.5) lib/gen_server.ex:1074: GenServer.call/3
    (chat 0.1.0) lib/chat/db/pipeline/writer.ex:40: Chat.Db.Pipeline.Writer.demand_queue/1
    (chat 0.1.0) lib/chat/db/pipeline/writer_process.ex:45: Chat.Db.Pipeline.WriterProcess.handle_continue/2
    (stdlib 5.1.1) gen_server.erl:1067: :gen_server.try_handle_continue/3
    (stdlib 5.1.1) gen_server.erl:977: :gen_server.loop/7
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:continue, :demand}
State: {:w_state, Chat.Db.InternalDb, "/root/db/v.9_files", Chat.Db.InternalDb.Queue, Chat.Db.InternalDb.Compactor, 0, nil}
```

**Comment by sergey-lukianov** [comment]
one more example
```
2024-02-11 20:25:22.244000 [error] GenServer Chat.Db.InternalDb.Writer terminating
** (stop) exited in: GenServer.call(Chat.Db.InternalDb.Queue, :demand, 5000)
    ** (EXIT) time out
    (elixir 1.15.5) lib/gen_server.ex:1074: GenServer.call/3
    (chat 0.1.0) lib/chat/db/pipeline/writer.ex:40: Chat.Db.Pipeline.Writer.demand_queue/1
    (chat 0.1.0) lib/chat/db/pipeline/writer_process.ex:45: Chat.Db.Pipeline.WriterProcess.handle_continue/2
    (stdlib 5.1.1) gen_server.erl:1067: :gen_server.try_handle_continue/3
    (stdlib 5.1.1) gen_server.erl:977: :gen_server.loop/7
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:continue, :demand}
State: {:w_state, Chat.Db.InternalDb, "/root/db/v.9_files", Chat.Db.InternalDb.Queue, Chat.Db.InternalDb.Compactor, 0, #Reference<0.3758285179.268959745.20877>}
2024-02-11 20:25:23.647000 [debug] wpa_supplicant: wlan0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
2024-02-11 20:25:23.647000 [debug] WPASupplicant ignoring {:event, "CTRL-EVENT-SUBNET-STATUS-UPDATE", %{"status" => "0"}}
2024-02-11 20:25:23.659000 [debug] wpa_supplicant: wlan0: AP-STA-CONNECTED c4:91:0c:a9:83:a1
2024-02-11 20:25:23.660000 [debug] wpa_supplicant: wlan0: EAPOL-4WAY-HS-COMPLETED c4:91:0c:a9:83:a1
2024-02-11 20:25:23.660000 [debug] wpa_supplicant(wlan0): EAPOL-4WAY-HS-COMPLETED c4:91:0c:a9:83:a1
2024-02-11 20:25:23.779000 [debug] udhcpd: udhcpd: sending ACK to 192.168.25.137
2024-02-11 20:25:25.828000 [debug] udhcpd: udhcpd: sending ACK to 192.168.25.137
2024-02-11 20:25:27.249000 [error] GenServer Chat.Db.InternalDb.Writer terminating
** (stop) exited in: GenServer.call(Chat.Db.InternalDb.Queue, :demand, 5000)
    ** (EXIT) time out
    (elixir 1.15.5) lib/gen_server.ex:1074: GenServer.call/3
    (chat 0.1.0) lib/chat/db/pipeline/writer.ex:40: Chat.Db.Pipeline.Writer.demand_queue/1
    (chat 0.1.0) lib/chat/db/pipeline/writer_process.ex:45: Chat.Db.Pipeline.WriterProcess.handle_continue/2
    (stdlib 5.1.1) gen_server.erl:1067: :gen_server.try_handle_continue/3
    (stdlib 5.1.1) gen_server.erl:977: :gen_server.loop/7
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:continue, :demand}
State: {:w_state, Chat.Db.InternalDb, "/root/db/v.9_files", Chat.Db.InternalDb.Queue, Chat.Db.InternalDb.Compactor, 0, nil}
```

**Comment by sergey-lukianov** [comment]
```
2024-02-11 20:25:35.750000 [error] GenServer Chat.Db.InternalDb.Writer terminating
** (stop) exited in: GenServer.call(Chat.Db.InternalDb.Queue, :demand, 5000)
    ** (EXIT) time out
    (elixir 1.15.5) lib/gen_server.ex:1074: GenServer.call/3
    (chat 0.1.0) lib/chat/db/pipeline/writer.ex:40: Chat.Db.Pipeline.Writer.demand_queue/1
    (chat 0.1.0) lib/chat/db/pipeline/writer_process.ex:45: Chat.Db.Pipeline.WriterProcess.handle_continue/2
    (stdlib 5.1.1) gen_server.erl:1067: :gen_server.try_handle_continue/3
    (stdlib 5.1.1) gen_server.erl:977: :gen_server.loop/7
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:continue, :demand}
State: {:w_state, Chat.Db.InternalDb, "/root/db/v.9_files", Chat.Db.InternalDb.Queue, Chat.Db.InternalDb.Compactor, 2, #Reference<0.3758285179.268697602.138888>}
```
