### ISSUE TITLE
Error processing room requests?

### ISSUE THREAD

**Issue by sergey-lukianov** [Buckitup-chat/chat#634]
```
2024-04-10 16:45:32.795000 [error] GenServer #PID<0.9805.0> terminating
** (FunctionClauseError) no function clause matching in ChatWeb.MainLive.Layout.Message."message (overridable 1)"/1
    (chat 0.1.0) lib/chat_web/live/main_live/layout/message.ex:163: ChatWeb.MainLive.Layout.Message."message (overridable 1)"(%{file: %{name: "1712767475.jpg", size: "91.2 Kb", url: "/get/file/2acca3bbdb7c3fc65def3d47cbc62fe72fc35d5c4a764e90ce3076fbd6c81977?a=wObTBZVjMfkZ1WSsXba83lxnciHGw9Nd1t0R8xFfqn0%3D"}, msg: %Chat.Rooms.PlainMessage{author_key: <<3, 105, 66, 194, 127, 39, 40, 114, 59, 41, 31, 86, 204, 240, 149, 248, 88, 121, 215, 115, 218, 147, 237, 13, 248, 140, 104, 150, 198, 192, 46, 63, 104>>, content: "wObTBZVjMfkZ1WSsXba83lxnciHGw9Nd1t0R8xFfqn0qzKO723w_xl3vPUfLxi_nL8NdXEp2TpDOMHb71sgZdw==", type: :image, timestamp: 1712767475, id: "8eacc1fb-04bf-40eb-a81a-340d92f2be66", index: 1}, author: false, color: "bg-white", timezone: "Europe/Riga", receiver: nil, linked: false, __changed__: nil, __given__: %{file: %{name: "1712767475.jpg", size: "91.2 Kb", url: "/get/file/2acca3bbdb7c3fc65def3d47cbc62fe72fc35d5c4a764e90ce3076fbd6c81977?a=wObTBZVjMfkZ1WSsXba83lxnciHGw9Nd1t0R8xFfqn0%3D"}, msg: %Chat.Rooms.PlainMessage{author_key: <<3, 105, 66, 194, 127, 39, 40, 114, 59, 41, 31, 86, 204, 240, 149, 248, 88, 121, 215, 115, 218, 147, 237, 13, 248, 140, 104, 150, 198, 192, 46, 63, 104>>, content: "wObTBZVjMfkZ1WSsXba83lxnciHGw9Nd1t0R8xFfqn0qzKO723w_xl3vPUfLxi_nL8NdXEp2TpDOMHb71sgZdw==", type: :image, timestamp: 1712767475, id: "8eacc1fb-04bf-40eb-a81a-340d92f2be66", index: 1}, author: false, color: "bg-white", timezone: "Europe/Riga", receiver: nil, linked: false, __changed__: nil, is_mine?: false, room: #Chat.Rooms.Room<name: "notblank4", type: :request, ...>, chat_type: :room, room_keys: [], export?: false, linkable?: false}, is_mine?: false, room: #Chat.Rooms.Room<name: "notblank4", type: :request, ...>, chat_type: :room, room_keys: [], export?: false, linkable?: false})
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/tag_engine.ex:68: Phoenix.LiveView.TagEngine.component/3
    (chat 0.1.0) lib/chat_web/live/main_live/layout/message.ex:92: anonymous fn/2 in ChatWeb.MainLive.Layout.Message."message_block (overridable 1)"/1
    (chat 0.1.0) /Volumes/cs_fs/buckitUp/chat/lib/chat_web/live/main_live/rooms.html.heex:177: ChatWeb.MainLive.Index.rooms/1
    (elixir 1.15.5) lib/enum.ex:1819: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/diff.ex:438: Phoenix.LiveView.Diff.traverse/7
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F8T4_GLzE3l42wEj", event: "event", payload: %{"event" => "room/switch", "type" => "click", "value" => %{"room" => "036962be54d6f8994bddb388555a15202d59e1c514ec502d088257d27bfa0ea386", "value" => ""}}, ref: "13", join_ref: "4"}
State: %{socket: #Phoenix.LiveView.Socket<id: "phx-F8T4_GLzE3l42wEj", endpoint: ChatWeb.Endpoint, view: ChatWeb.MainLive.Index, parent_pid: nil, root_pid: #PID<0.9805.0>, router: ChatWeb.Router, assigns: %{last_loaded_index: 6, is_room_linked?: false, users: [#Chat.Card<name: "What I Recycle (drop here)", ...>, #Chat.Card<name: "126", ...>, #Chat.Card<name: "24.1", ...>, #Chat.Card<name: "AlexG", ...>, #Chat.Card<name: "Booth 300", ...>, #Chat.Card<name: "Booth- 84", ...>, #Chat.Card<name: "Chris", ...>, #Chat.Card<name: "Crispin", ...>, #Chat.Card<name: "Daria", ...>, #Chat.Card<name: "Elena", ...>, #Chat.Card<name: "JohnDoe", ...>, #Chat.Card<name: "Maria", ...>, #Chat.Card<name: "Mary", ...>, #Chat.Card<name: "Mau", ...>, #Chat.Card<name: "Mihail Chetveruhin", ...>, #Chat.Card<name: "S brave", ...>, #Chat.Card<name: "S22", ...>, #Chat.Card<name: "Silan", ...>, #Chat.Card<name: "Silan", ...>, #Chat.Card<name: "Surya", ...>, #Chat.Card<name: "Vadim", ...>, #Chat.Card<name: "a1b", ...>, #Chat.Card<name: "ark", ...>, #Chat.Card<name: "arka", ...>, #Chat.Card<name: "bot", ...>, #Chat.Card<name: "brave new", ...>, #Chat.Card<name: "brevebrave", ...>, #Chat.Card<name: "cargouser", ...>, #Chat.Card<name: "cargouser2", ...>, #Chat.Card<name: "chemodan_checkpoin", ...>, #Chat.Card<name: "chrom", ...>, #Chat.Card<name: "from mobile zt", ...>, #Chat.Card<name: "ggg", ...>, #Chat.Card<name: "in_lan", ...>, #Chat.Card<name: "kitchen", ...>, #Chat.Card<name: "me", ...>, #Chat.Card<name: "me", ...>, #Chat.Card<name: "me here", ...>, #Chat.Card<...>, ...], edit_content: nil, timezone: "Europe/Riga", uploads_metadata: %{}, __changed__: %{}, timezone_offset: 3, edit_room: nil, has_more_messages: false, cargo_room: %Chat.Sync.CargoRoom{pub_key: <<3, 105, 98, 190, 84, 214, 248, 153, 75, 221, 179, 136, 85, 90, 21, 32, 45, 89, 225, 197, 20, 236, 80, 45, 8, 130, 87, 210, 123, 250, ...>>, successful?: true, timer_ref: nil, status: :complete, timer: 300}, page: 0, monotonic_offset: 2289192089, db_status: %{flags: [replication: false, cargo: false], mode: :main, writable: :yes, compacting: false}, logout_step: nil, room_requests: [], lobby_mode: :rooms, joined_rooms: [#Chat.Rooms.Room<name: "cargo0", type: :request, ...>, #Chat.Rooms.Room<name: "cargo1(metal)", type: :request, ...>, #Chat.Rooms.Room<name: "cargoFAT", type: :request, ...>, #Chat.Rooms.Room<name: "cargoFAT-2", type: :request, ...>, #Chat.Rooms.Room<name: "noblank1", type: :request, ...>, #Chat.Rooms.Room<name: "notblank", type: :request, ...>, #Chat.Rooms.Room<name: "notblank4", type: :request, ...>, #Chat.Rooms.Room<name: "screencast", type: :public, ...>, #Chat.Rooms.Room<name: "true_cargo_09-04", type: :request, ...>, #Chat.Rooms.Room<name: "useful things 2", type: :private, ...>], backup_settings: %Chat.Admin.BackupSettings{type: :regular}, usb_drive_dump_room: nil, operating_system: "Mac OS X", search_filter: :off, messages: [], mode: :lobby, image_gallery: nil, file_uploads_order: [], last_load_timestamp: 1, cargo_settings: %Chat.Admin.CargoSettings{checkpoints: [#Chat.Card<name: "cargouser2", ...>, #Chat.Card<name: "cargouser", ...>, #Chat.Card<name: "What I Recycle (drop here)", ...>, #Chat.Card<name: "Booth- 84", ...>], camera_sensors: ["http://user1:12345qwert@192.168.24.65/"], weight_sensor: %{name: "/dev/ttyUSB0", type: "NCI", speed: 19200, parity: "odd", data_bits: 7, stop_bits: 1}}, room_count_to_backup: 59, new_rooms: [], dialog: nil, cargo_sync: :enabled, room: #Chat.Rooms.Room<name: "notblank", type: :request, ...>, room_identity: #Chat.Identity<name: "", ...>, me: #Chat.Identity<name: "What I Recycle (drop here)", ...>, media_settings: %Chat.Admin.MediaSettings{functionality: :cargo, main: false}, live_modal: nil, live_action: :index, need_login: false, input_mode: :plain, locale: "ru", room_map: %{...}, ...}, transport_pid: #PID<0.9803.0>, ...>, components: {%{1 => {ChatWeb.MainLive.Page.RoomForm, :room_form, %{id: :room_form, changeset: #Ecto.Changeset<action: nil, changes: %{}, errors: [name: {"can't be blank", [validation: :required]}], data: #Chat.Rooms.RoomInput<>, valid?: false>, flash: %{}, __changed__: %{}, myself: %Phoenix.LiveComponent.CID{cid: 1}, media_settings: %Chat.Admin.MediaSettings{functionality: :cargo, main: false}, cargo_room: %Chat.Sync.CargoRoom{pub_key: <<3, 105, 98, 190, 84, 214, 248, 153, 75, 221, 179, 136, 85, 90, 21, 32, 45, 89, 225, 197, 20, 236, 80, 45, 8, 130, 87, 210, 123, 250, 14, 163, 134>>, successful?: true, timer_ref: nil, status: :complete, timer: 300}, usb_drive_dump_room: nil}, %{lifecycle: %Phoenix.LiveView.Lifecycle{handle_event: [], handle_info: [], handle_params: [], mount: [], after_render: []}, live_temp: %{}, root_view: ChatWeb.MainLive.Index}, {140407226147510945925288435328571054751, %{0 => {35643132190049764274821854854233288313, %{3 => {115057119939996088977429396889008618145, %{1 => {287501741127416623641972240022198642248, %{}}, 2 => {158581258674367449563809690815114980385, %{}}, 3 => {158581258674367449563809690815114980385, %{}}, 4 => {158581258674367449563809690815114980385, %{}}, 5 => {60291362168049941233796897811374326263, %{0 => {158581258674367449563809690815114980385, %{}}}}, 6 => {287501741127416623641972240022198642248, %{}}, 7 => {290625419043380033800101826384089593375, %{ (truncated)
```

**Comment by sergey-lukianov** [comment]
```elixir
%{
  file: %{
    name: "1712767475.jpg",
    size: "91.2 Kb", 
    url: "/get/file/2acca3bbdb7c3fc65def3d47cbc62fe72fc35d5c4a764e90ce3076fbd6c81977?a=wObTBZVjMfkZ1WSsXba83lxnciHGw9Nd1t0R8xFfqn0%3D"
  }, 
  msg: %Chat.Rooms.PlainMessage{
    author_key: <<3, 105, 66, 194, 127, 39, 40, 114, 59, 41, 31, 86, 204, 240, 149, 248, 88, 121, 215, 115, 218, 147, 237, 13, 248, 140, 104, 150, 198, 192, 46, 63, 104>>, 
    content: "wObTBZVjMfkZ1WSsXba83lxnciHGw9Nd1t0R8xFfqn0qzKO723w_xl3vPUfLxi_nL8NdXEp2TpDOMHb71sgZdw==", 
    type: :image, 
    timestamp: 1712767475, 
    id: "8eacc1fb-04bf-40eb-a81a-340d92f2be66", 
    index: 1
  }, 
  author: false, 
  color: "bg-white", 
  timezone: "Europe/Riga", 
  receiver: nil, 
  linked: false, 
  __changed__: nil, 
  __given__: %{
    file: %{
      name: "1712767475.jpg", 
      size: "91.2 Kb", 
      url: "/get/file/2acca3bbdb7c3fc65def3d47cbc62fe72fc35d5c4a764e90ce3076fbd6c81977?a=wObTBZVjMfkZ1WSsXba83lxnciHGw9Nd1t0R8xFfqn0%3D"
    }, 
    msg: %Chat.Rooms.PlainMessage{
      author_key: <<3, 105, 66, 194, 127, 39, 40, 114, 59, 41, 31, 86, 204, 240, 149, 248, 88, 121, 215, 115, 218, 147, 237, 13, 248, 140, 104, 150, 198, 192, 46, 63, 104>>, 
      content: "wObTBZVjMfkZ1WSsXba83lxnciHGw9Nd1t0R8xFfqn0qzKO723w_xl3vPUfLxi_nL8NdXEp2TpDOMHb71sgZdw==", 
      type: :image, 
      timestamp: 1712767475, 
      id: "8eacc1fb-04bf-40eb-a81a-340d92f2be66", 
      index: 1
    },
    author: false, 
    color: "bg-white", 
    timezone: "Europe/Riga", 
    receiver: nil, 
    linked: false, 
    __changed__: nil, 
    is_mine?: false, 
    room: #Chat.Rooms.Room<name: "notblank4", type: :request, ...>, 
    chat_type: :room, 
    room_keys: [], 
    export?: false, 
    linkable?: false
  }, 
  is_mine?: false, 
  room: #Chat.Rooms.Room<name: "notblank4", type: :request, ...>, 
  chat_type: :room, 
  room_keys: [], 
  export?: false, 
  linkable?: false
}
```

```
